export type PlanStatus =
  "草稿" | "待确认" | "待会签" | "审核中" | "已退回" | "已定版" | "已废止";
export type Parameter = {
  name: string;
  value: string;
  unit: string;
  source: string;
  confirmed: boolean;
};
export type Evidence = {
  id: string;
  type: string;
  title: string;
  content: string;
  sourceId?: string;
  href?: string;
};
export type Plan = {
  id: string;
  familyId: string;
  projectId: string;
  project: string;
  title: string;
  goal: string;
  hypothesis: string;
  method: string;
  materials: string;
  sampleCount: number;
  repeats: number;
  control: string;
  parameters: Parameter[];
  steps: string[];
  equipmentId: string;
  characterization: string;
  output: string;
  risks: string[];
  evidence: Evidence[];
  version: number;
  status: PlanStatus;
  route: string;
  owner: string;
  updatedAt: string;
  reviews: { action: string; content: string; time: string; author: string }[];
  messages: { role: "user" | "assistant"; content: string }[];
};
export type Sample = {
  id: string;
  projectId: string;
  name: string;
  batch: string;
  type: string;
  quantity: number;
  unit: string;
  status: string;
  storage: string;
  location: string;
  taskId: string;
  eln: string;
  lims: string;
  traces: string[];
};
export type Equipment = {
  id: string;
  name: string;
  type: string;
  status: string;
  access: string;
  range: string;
  organization: string;
  sharing: string;
  hours: string;
  condition: string;
  owner: string;
  source: string;
};
export type Booking = {
  id: string;
  projectId: string;
  planId: string;
  taskId: string;
  equipmentId: string;
  date: string;
  start: number;
  end: number;
  sampleId: string;
  owner: string;
  purpose: string;
  status: string;
};
export type Task = {
  id: string;
  projectId: string;
  planId: string;
  name: string;
  batch: string;
  owner: string;
  status: string;
  step: number;
  sampleIds: string[];
  equipmentId: string;
  checks: string[];
  createdAt: string;
  updatedAt: string;
  logs: string[];
  exceptions: {
    id: string;
    stage: string;
    description: string;
    resolved: boolean;
    resolution: string;
    time: string;
  }[];
  changes: {
    name: string;
    old: string;
    value: string;
    reason: string;
    author: string;
    time: string;
    approved: boolean;
  }[];
  parameters: Parameter[];
  resultId: string;
};
export type Point = { x: number; a: number; b: number; computed: number };
export type Result = {
  id: string;
  projectId: string;
  taskId: string;
  sampleId: string;
  name: string;
  method: string;
  points: Point[];
  processed: boolean;
  operations: string[];
  report: string;
  confirmed: boolean;
  createdAt: string;
};
export type Transfer = {
  id: string;
  projectId: string;
  resultId: string;
  direction: string;
  content: string;
  targetId: string;
  href: string;
  time: string;
};
export type DoState = {
  plans: Plan[];
  samples: Sample[];
  equipment: Equipment[];
  bookings: Booking[];
  tasks: Task[];
  results: Result[];
  transfers: Transfer[];
};
