'use client';
import { useEffect, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { ArrowRight, Bot, Check, CheckCircle2, Database, FileText, GitBranch, Layers, LoaderCircle, Pencil, Play, Quote, Save, Send, ShieldCheck, Square } from 'lucide-react';
import { useComputeStore } from './store';
import { Button, Modal, PageHeader, Panel, Status, Tabs, downloadFile } from './ui';
import type { ComputePlan } from './types';

const steps = ['明确计算目标','识别输入与约束','推荐计算方法','推荐工具 / 软件','生成参数方案','评估资源需求','生成计算方案','创建计算任务'];
const artifactTabs = ['计算方案','数据','方法','参数','工具','资源','输出'];

export function ComputeAgent() {
  const s = useComputeStore(); const query = useSearchParams(); const router = useRouter();
  const plan = s.plans.find(p=>p.id===query.get('plan')) || s.plans.find(p=>p.id===s.activePlanId) || s.plans[0];
  const [tab,setTab] = useState('计算方案'); const [running,setRunning] = useState(false); const [stage,setStage] = useState(plan.status==='草稿'?0:7); const [message,setMessage] = useState(''); const [reply,setReply] = useState(''); const [editing,setEditing] = useState(false); const [confirm,setConfirm] = useState(false); const [checked,setChecked] = useState<string[]>([]); const [evidence,setEvidence] = useState(false); const [notice,setNotice] = useState(''); const [draft,setDraft] = useState<ComputePlan>(structuredClone(plan));
  const tool = s.tools.find(t=>t.id===plan.toolId); const dataset = s.datasets.find(d=>d.id===plan.datasetId); const model = s.models.find(m=>m.id===plan.modelId); const tasks = s.tasks.filter(t=>t.planId===plan.id); const ready = stage>=7 || plan.status!=='草稿';
  useEffect(()=> { if(!running) return; const timer = window.setInterval(()=>setStage(v=>Math.min(7,v+1)),700); return ()=>window.clearInterval(timer); },[running]);
  useEffect(()=> { if(stage>=7 && running) {setRunning(false);s.updatePlan(plan.id,{status:'待确认'});setNotice('计算方案已生成。请核对方法、参数与资源后创建正式任务。');} },[stage,running,plan.id,s]);
  function start(){setStage(0);setRunning(true);setNotice('');}
  function saveEdit(){if(!draft.title.trim()||!draft.goal.trim()){setNotice('方案名称与研究目标不能为空。');return;}s.updatePlan(plan.id,{...draft,status:'待确认',parameters:draft.parameters.map((p,i)=>p.value!==plan.parameters[i]?.value?{...p,original:plan.parameters[i]?.original||plan.parameters[i]?.value,source:'人工输入值',modifiedBy:'张博士',modifiedAt:new Date().toLocaleString('sv-SE')}:p)});setEditing(false);setNotice('方案已保存，修改后的内容需要重新确认。');}
  function create(){s.updatePlan(plan.id,{status:'已确认'}); const id = s.createTask(plan.id);if(!id){setNotice('无法创建任务，请检查工具上架状态和许可证。');setConfirm(false);return;}setConfirm(false);router.push(`/compute-space/tasks/${id}`);}
  function send(){if(!message.trim())return;setReply(message);s.updatePlan(plan.id,{goal:`${plan.goal}\n补充要求：${message}`,status:'待确认'});setMessage('');setStage(7);setNotice('补充要求已写入方案研究目标，请在右侧检查并编辑参数。');}
  const confirmationItems = ['已确认计算方法与参数来源','已确认资源申请与预计运行时长','已确认软件许可证调用','已确认批量参数组合与风险范围'];
  return <div data-prd-id="REQ-AGENT-001"><PageHeader eyebrow="开始计算 / 科研计算助手" title={plan.title} description={`${plan.project} · ${plan.id} · 计算方案 V${plan.version}`} actions={<><Status value={plan.status}/><Button onClick={()=>{s.updatePlan(plan.id,{});setNotice('方案已保存至当前浏览器，可随时恢复。');}}><Save/>保存方案</Button><Button variant="primary" disabled={!ready||running} onClick={()=>{setChecked([]);setConfirm(true);}}>创建计算任务<ArrowRight/></Button></>}/>
    {notice&&<div role="status" className="cp-note" style={{marginBottom:16}}>{notice}</div>}
    <div className="cp-agent-layout"><Panel title="任务与上下文"><div className="cp-context-item" style={{paddingTop:0}}><span>计算目标</span><p>{plan.goal}</p></div><div className="cp-context-item"><span>科学假设</span><p>{plan.hypothesis}</p></div><div className="cp-context-item"><span>输入资源</span><Link className="cp-row cp-muted" style={{marginBottom:8}} href="/compute-space/data"><Database size={14}/>{dataset?.name} V{dataset?.version}</Link><Link className="cp-row cp-muted" style={{marginBottom:8}} href="/compute-space/models"><Layers size={14}/>{model?.name||'未绑定模型'}</Link><button className="cp-row cp-muted" onClick={()=>setEvidence(true)}><Quote size={14}/>{plan.evidence.length} 项研究依据</button></div><div style={{paddingTop:16}}><h3 style={{fontSize:12,marginBottom:8}}>任务计划</h3>{steps.map((step,i)=><div key={step} className={`cp-step ${i<stage?'done':''} ${i===stage?'active':''}`}><span>{i<stage?<Check size={12}/>:i+1}</span><strong>{step}</strong></div>)}</div><div className="cp-note" style={{marginTop:12}}>专业任务页负责运行、日志与结果。此处先完成方案规划和人工确认。</div></Panel>
    <Panel title={<span className="cp-row"><Bot size={17}/>科研计算助手</span>} actions={<span className="cp-badge">方案规划</span>}><div className="cp-user-message">{plan.goal}</div>{stage===0&&!running?<div className="cp-stack"><div className="cp-agent-event"><h3><Bot size={16}/>准备开始计算规划</h3><p>我将结合当前科研上下文，识别输入和约束，推荐方法与工具，并生成结构化计算方案。</p></div><Button variant="primary" onClick={start}><Play/>开始分析</Button><div className="cp-muted">演示分析约 5 秒，可暂停后继续。</div></div>:<><div className="cp-agent-event"><h3><CheckCircle2 size={16}/>明确研究目标</h3><p>将研究问题拆解为可验证的计算指标：{plan.outputs.join('、')}。研究依据和输入版本随方案保存。</p></div>{stage>=2&&<div className="cp-agent-event"><h3><CheckCircle2 size={16}/>方法与工具推荐</h3><p>建议使用{plan.method}。{tool?.name}支持对应求解器，已接入平台，当前许可状态为“{tool?.license}”。</p><Link href={`/compute-space/tools/${tool?.id}`} className="cp-link" style={{fontSize:12,display:'block',marginTop:10}}>查看软件能力和输入输出</Link></div>}{stage>=4&&<div className="cp-agent-event"><h3><CheckCircle2 size={16}/>参数与边界条件</h3><p>已组织 {plan.parameters.length} 项参数；区分文献、实验、领域默认与 AI 推荐来源。建议优先使用已验证的材料参数，并对 AI 推荐范围进行人工核对。</p><Button variant="ghost" onClick={()=>setTab('参数')}>查看结构化参数<ArrowRight/></Button></div>}{stage>=6&&<div className="cp-agent-event"><h3><CheckCircle2 size={16}/>资源与风险评估</h3><p>{plan.resources}。{plan.risks}</p></div>}{ready&&<div className="cp-note"><div className="cp-row" style={{fontWeight:600,marginBottom:6}}><ShieldCheck size={16}/>等待人工确认</div>右侧方案可编辑、保存或生成新版本。正式任务仅在确认后提交。</div>}{running&&<div className="cp-row cp-muted" style={{marginTop:15}}><LoaderCircle size={14} className="animate-spin"/>{steps[stage]}<Button variant="ghost" onClick={()=>setRunning(false)}><Square/>暂停</Button></div>}{!running&&!ready&&<Button onClick={()=>setRunning(true)}>继续分析</Button>}</>}{reply&&<div className="cp-user-message" style={{marginTop:20}}>补充要求：{reply}</div>}<div style={{borderTop:'1px solid #e8ebef',paddingTop:16,marginTop:22}}><label className="cp-field"><span>补充要求或调整方案</span><textarea className="cp-input" rows={3} value={message} onChange={e=>setMessage(e.target.value)} placeholder="例如：将内存改为 256 GB，增加 200 ℃工况"/></label><div className="cp-row" style={{justifyContent:'flex-end',marginTop:10}}><Button disabled={!message.trim()} onClick={send}><Send/>发送要求</Button></div></div></Panel>
    <section className="cp-panel cp-agent-artifact"><div className="cp-panel-heading"><h2 className="cp-row"><FileText size={16}/>计算方案 Artifact</h2><Button variant="ghost" onClick={()=>{setDraft(structuredClone(plan));setEditing(true);}}><Pencil/>修改方案</Button></div><div className="cp-panel-body"><Tabs items={artifactTabs} value={tab} onChange={setTab}/><div className="cp-artifact-heading"><FileText size={24}/><div><h2>科研计算方案 V{plan.version}</h2><span className="cp-muted">{ready?'已生成 · 待核对与确认':'方案草稿 · 随分析逐步完善'}</span></div></div>
    {tab==='计算方案'&&<><div className="cp-artifact-section"><h3>研究目标</h3><p>{plan.goal}</p></div><div className="cp-artifact-section"><h3>计算方法</h3><p>{plan.method}</p><p>软件：{tool?.name} {tool?.version}</p></div><div className="cp-artifact-section"><h3>输入与版本</h3><p>{dataset?.name} V{dataset?.version} · {dataset?.rows.toLocaleString()} 条</p><p>{model?.name} V{model?.version}</p></div><div className="cp-artifact-section"><h3>关键参数</h3>{plan.parameters.slice(0,3).map(p=><div key={p.name} className="cp-row" style={{justifyContent:'space-between',fontSize:12,marginTop:7}}><span className="cp-muted">{p.name}</span><span>{p.value} {p.unit}</span></div>)}</div><div className="cp-artifact-section"><h3>风险与科学边界</h3><p>{plan.risks}</p></div><div className="cp-artifact-section"><h3>来源依据</h3><p>{plan.evidence.join('；')}</p></div></>}
    {tab==='数据'&&<div className="cp-stack"><label className="cp-field"><span>输入数据版本</span><select className="cp-select" value={plan.datasetId} onChange={e=>s.updatePlan(plan.id,{datasetId:e.target.value,status:'待确认'})}>{s.datasets.map(d=><option key={d.id} value={d.id}>{d.name} V{d.version}</option>)}</select></label><div className="cp-note">当前版本质量 {dataset?.quality}% · 来源 {dataset?.source}。版本引用固定，不随新版本自动替换。</div><label className="cp-field"><span>使用模型版本</span><select className="cp-select" value={plan.modelId} onChange={e=>s.updatePlan(plan.id,{modelId:e.target.value,status:'待确认'})}>{s.models.map(m=><option key={m.id} value={m.id}>{m.name} V{m.version}</option>)}</select></label><Link href="/compute-space/data" className="cp-link">处理数据并生成新版本</Link></div>}
    {tab==='方法'&&<div className="cp-stack"><h3>{plan.method}</h3><p className="cp-muted">依据已引用的科研问题与边界条件，进行热-力耦合建模；通过网格独立性与文献基准对照验证求解稳定性。</p><label className="cp-field"><span>选择计算方法</span><select className="cp-select" value={plan.method} onChange={e=>s.updatePlan(plan.id,{method:e.target.value,status:'待确认'})}>{[plan.method,'热-力耦合有限元模拟','离散元模拟（DEM）','相场法（Phase Field）','多目标候选筛选','物理信息神经网络（PINN）'].filter((v,i,a)=>a.indexOf(v)===i).map(m=><option key={m}>{m}</option>)}</select></label><Button onClick={()=>setEvidence(true)}><Quote/>查看方法依据</Button></div>}
    {tab==='参数'&&<div className="cp-table-wrap"><table className="cp-table" style={{whiteSpace:'normal'}}><thead><tr><th>参数</th><th>值 / 单位</th><th>来源</th></tr></thead><tbody>{plan.parameters.map(p=><tr key={p.name}><td>{p.name}</td><td>{p.value} {p.unit}</td><td style={{fontSize:10}}>{p.source}</td></tr>)}</tbody></table><p className="cp-muted" style={{marginTop:14}}>修改参数后需重新确认；实际运行值将单独固化到任务。</p></div>}
    {tab==='工具'&&<div className="cp-stack"><label className="cp-field"><span>执行工具</span><select className="cp-select" value={plan.toolId} onChange={e=>s.updatePlan(plan.id,{toolId:e.target.value,status:'待确认'})}>{s.tools.map(t=><option key={t.id} value={t.id}>{t.name} · {t.license}</option>)}</select></label><h3>{tool?.name} {tool?.version}</h3><p className="cp-muted">{tool?.description}</p><Status value={tool?.license||'未配置'}/><div className="cp-note">推荐原因：支持当前计算方法与输出指标；已接入科研平台；使用前校验许可与运行环境。</div><Link href={`/compute-space/tools/${tool?.id}`} className="cp-link">查看工具详情</Link></div>}
    {tab==='资源'&&<div className="cp-stack"><label className="cp-field"><span>资源建议</span><select className="cp-select" value={plan.resources} onChange={e=>s.updatePlan(plan.id,{resources:e.target.value,status:'待确认'})}>{[plan.resources,'CPU 32 核 / 内存 128 GB / 预计 2 小时','CPU 64 核 / 内存 256 GB / 预计 1 小时','GPU A100 × 2 / 内存 128 GB / 预计 40 分钟'].filter((v,i,a)=>a.indexOf(v)===i).map(r=><option key={r}>{r}</option>)}</select></label><div className="cp-artifact-section"><h3>运行环境</h3><p>{tool?.environment}</p></div><div className="cp-alert">高成本资源、软件许可证与批量参数任务均需要在提交前人工确认。</div></div>}
    {tab==='输出'&&<div className="cp-stack">{plan.outputs.map(o=><div key={o} className="cp-row"><CheckCircle2 size={15} color="#51846e"/>{o}</div>)}<div className="cp-note">评价方式：固定工况与文献/实测数据对照；保留误差范围、适用边界及人工分析状态。</div><Button onClick={()=>downloadFile(`${plan.id}.json`,JSON.stringify(plan,null,2),'application/json')}><Save/>导出计算方案</Button></div>}
    </div><div className="cp-plan-actions"><Button onClick={()=>{const id=s.newPlanVersion(plan.id);router.push(`/compute-space/agent?plan=${id}`);setStage(7);setNotice('已创建独立方案版本。');}}><GitBranch/>新版本</Button><Button variant="primary" disabled={!ready||running} onClick={()=>{setChecked([]);setConfirm(true);}}>确认并创建任务</Button></div></section></div>
    {tasks.length>0&&<Panel title="此方案已创建的计算任务" className="mt-5"><div className="cp-row">{tasks.map(t=><Link key={t.id} href={`/compute-space/tasks/${t.id}`} className="cp-button">{t.name}<Status value={t.status}/></Link>)}</div></Panel>}
    <Modal open={editing} onClose={()=>setEditing(false)} title={`编辑计算方案 V${plan.version}`} footer={<><Button onClick={()=>setEditing(false)}>取消</Button><Button variant="primary" onClick={saveEdit}>保存修改</Button></>}><div className="cp-stack"><label className="cp-field"><span>方案名称</span><input className="cp-input" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="cp-field"><span>研究目标</span><textarea className="cp-input" rows={3} value={draft.goal} onChange={e=>setDraft({...draft,goal:e.target.value})}/></label><label className="cp-field"><span>科学假设</span><input className="cp-input" value={draft.hypothesis} onChange={e=>setDraft({...draft,hypothesis:e.target.value})}/></label>{draft.parameters.map((p,i)=><label className="cp-field" key={p.name}><span>{p.name}（{p.unit}）</span><input className="cp-input" value={p.value} onChange={e=>setDraft({...draft,parameters:draft.parameters.map((v,j)=>j===i?{...v,value:e.target.value}:v)})}/></label>)}<label className="cp-field"><span>风险与约束</span><textarea className="cp-input" value={draft.risks} onChange={e=>setDraft({...draft,risks:e.target.value})}/></label></div></Modal>
    <Modal open={confirm} onClose={()=>setConfirm(false)} title="创建正式计算任务 · 人工确认" footer={<><Button onClick={()=>setConfirm(false)}>返回修改</Button><Button variant="primary" disabled={checked.length!==4||!tool||tool.status!=='已上架'||/过期|不可用/.test(tool.license)} onClick={create}>确认提交计算任务</Button></>}><div className="cp-stack"><div className="cp-note">{plan.title} · 方案 V{plan.version}<br/>{plan.method}<br/>{dataset?.name} V{dataset?.version}<br/>{plan.resources}</div><div className="cp-row"><span>许可证</span><Status value={tool?.license||'未配置'}/></div><div className="cp-alert">{plan.risks}</div>{confirmationItems.map(item=><label className="cp-row" key={item}><input type="checkbox" checked={checked.includes(item)} onChange={e=>setChecked(e.target.checked?[...checked,item]:checked.filter(v=>v!==item))}/><span>{item}</span></label>)}<p className="cp-muted">确认人：张博士。确认记录及所有输入版本将保存在任务追溯中。此环境使用模拟资源，不产生真实计算费用。</p></div></Modal>
    <Modal open={evidence} onClose={()=>setEvidence(false)} title="研究依据与来源"><div className="cp-stack">{plan.evidence.map((v,i)=><div className="cp-note" key={`${v}-${i}`}><strong>{v}</strong><p style={{marginTop:8}}>演示研究证据 · 与当前方案 V{plan.version} 关联。参数来源类型已记录在参数表中，提交前请结合原始研究资料核对。</p></div>)}<Link className="cp-button" href="/compute-space/handoff?direction=read">返回读空间补充研究</Link></div></Modal>
  </div>;
}

