'use client';
import { useRef, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowRight, ArrowUpRight, Bot, Boxes, ChartNoAxesCombined, Check, ChevronRight, Cpu, Database, FileText, FlaskConical, Layers, Paperclip, Plus, Quote, Sparkles, X } from 'lucide-react';
import { useComputeStore } from './store';
import { Button, Modal, PageHeader, Panel, Status } from './ui';
import { useResearchProject } from '@/components/research/workspace-kit';

const workspaces = [ { title: '智能设计与筛选', desc: '探索候选空间\n发现最优参数组合', href: 'design', icon: Boxes }, { title: '计算任务', desc: '提交与监控运行\n追溯每一次计算', href: 'tasks', icon: Cpu }, { title: '科研数据处理', desc: '清洗与特征处理\n形成可靠数据版本', href: 'data', icon: Database }, { title: '模型训练与评价', desc: '训练与科学评价\n比较模型及版本', href: 'models', icon: ChartNoAxesCombined }, { title: '科研工具', desc: '发现科学软件\n调用专业计算能力', href: 'tools', icon: Layers } ];
const examples = ['模拟不同温度和围压组合对页岩裂缝扩展形态的影响，并找出最敏感的参数。', '筛选具有高活性与高稳定性的催化剂候选材料，比较配比与制备成本。', '使用已有实验数据训练裂缝长度预测模型，并在固定测试集上评价。'];

export function ComputeHome() {
  const s = useComputeStore(); const router = useRouter(); const { project } = useResearchProject();
  const [prompt, setPrompt] = useState(''); const [showRefs, setShowRefs] = useState(false); const [refTab, setRefTab] = useState('研究结论'); const [notice, setNotice] = useState(''); const fileRef = useRef<HTMLInputElement>(null);
  function start(goal = prompt) { if (!goal.trim()) { setNotice('请描述计算目标，或选择下方的示例问题。'); return; } const id = s.createPlan(goal.trim(), { project: project.name, projectId: project.id, evidence: [...s.references], title: goal.includes('页岩') ? '页岩温压耦合裂缝模拟' : goal.slice(0, 28) }); router.push(`/compute-space/agent?plan=${id}`); }
  const refs: Record<string, string[]> = { '研究结论': ['科学假设 H1：温度与围压共同改变裂缝破坏模式', '读空间研究结论：热损伤改变页岩裂缝扩展方向', '文献参数：弹性模量 28 GPa / 温度范围 25–250 ℃', `当前课题：${project.name}`], '科研数据': s.datasets.map(d => `${d.name} V${d.version} · ${d.rows.toLocaleString()} 行`), '模型': s.models.map(m => `${m.name} V${m.version} · ${m.type}`), '已有结果': s.tasks.filter(t => t.status === '已完成').map(t => `${t.name} · ${t.id}`), '实验数据': ['真三轴实验批次 EXP-0920 · 36 组', '高温岩石表征数据 · SEM / CT'] };
  return <div data-prd-id="REQ-HOME-001">
    <PageHeader title="开始计算" description="将科研问题转化为可执行计算方案，调用数据、模型与科学工具完成验证。" actions={<Link className="cp-button" href="/compute-space/tasks"><Cpu size={14}/>我的计算任务<ChevronRight size={14}/></Link>}/>
    <div className="cp-home-layout"><div className="cp-stack">
      <section><div className="cp-composer"><div className="cp-row" style={{justifyContent:'space-between',alignItems:'start'}}><h2>今天想解决什么计算问题？</h2><Sparkles size={20} color="#b4232d"/></div><textarea aria-label="计算目标" placeholder="描述你的计算目标，例如：模拟不同温度和围压组合对页岩裂缝扩展形态的影响，并找出最敏感的参数。" value={prompt} onChange={e => { setPrompt(e.target.value); setNotice(''); }}/><div className="cp-context-chips">{s.references.map(r => <span key={r} className="cp-context-chip"><FileText size={12}/>{r.length > 32 ? `${r.slice(0,32)}…` : r}<button onClick={() => s.removeReference(r)} aria-label={`移除引用 ${r}`}><X size={11}/></button></span>)}</div><div className="cp-composer-footer"><div className="cp-row"><Button variant="ghost" onClick={() => setShowRefs(true)}><Quote/>引用科研上下文</Button><Button variant="ghost" onClick={() => fileRef.current?.click()}><Paperclip/>上传文件</Button><input hidden ref={fileRef} type="file" accept=".csv,.txt,.json,.xlsx,.pdf" onChange={async e => { const file = e.target.files?.[0]; if (!file) return; s.addReference(`上传文件：${file.name}`); if (file.name.endsWith('.csv')) { const text = await file.text(); const rows = text.trim().split(/\r?\n/); const id = s.addDataset({ name: file.name.replace(/\.csv$/i, ''), version: 1, rows: Math.max(0,rows.length-1), columns: rows[0]?.split(',').length || 0, headers: rows[0]?.split(','), preview: rows.slice(1,7).map(row=>row.split(',')), quality: 0, source: `本地上传 · ${file.name}`, flow: ['已导入，待质量检查'], createdAt: new Date().toLocaleString('sv-SE'), creator: '张博士', usedBy: [] }); s.addReference(`已导入数据 ${id}`); } setNotice(`已引用 ${file.name}${file.name.endsWith('.csv') ? '，可在数据处理工作台查看' : '（演示保留文件名称与引用）'}`); e.target.value = ''; }}/></div><Button variant="primary" onClick={() => start()}>开始计算<ArrowRight/></Button></div></div>{notice && <p role="status" className="cp-muted" style={{marginTop:8}}>{notice}</p>}<div className="cp-quick-actions">{['生成计算方案','分析已有数据','设计参数组合','筛选候选材料/方案','运行模拟计算','训练一个科研模型','比较多个模型','解释已有计算结果'].map((name,i) => <button key={name} onClick={() => { const routes: Record<number,string> = {1:'data',2:'design',3:'design',5:'models',6:'models?view=compare',7:'analysis'}; if(routes[i]) router.push(`/compute-space/${routes[i]}`); else setPrompt(i===4 ? examples[0] : '基于科学假设 H1，生成一份验证页岩温压耦合破坏机制的计算方案。'); }}>{name}</button>)}</div></section>
      <div className="cp-agent-entry"><div className="cp-row" style={{flexWrap:'nowrap'}}><div className="cp-agent-icon"><Bot size={25}/></div><div><h2>科研计算助手</h2><p className="cp-muted" style={{marginTop:5}}>理解研究目标，推荐方法与工具，生成可追溯的计算方案。</p></div></div><Link className="cp-link cp-row" style={{fontSize:12,whiteSpace:'nowrap'}} href="/compute-space/agent">进入工作区<ArrowUpRight size={16}/></Link></div>
      <section><div className="cp-section-title"><h2>专业工作台</h2><span className="cp-muted">精细配置与执行管理</span></div><div className="cp-workspaces">{workspaces.map(w => <Link key={w.href} href={`/compute-space/${w.href}`} className="cp-workspace-entry"><w.icon size={22}/><strong>{w.title}</strong><p style={{whiteSpace:'pre-line'}}>{w.desc}</p></Link>)}</div></section>
      <section><div className="cp-section-title"><h2>最近计算任务 <span className="cp-muted" style={{fontWeight:400,marginLeft:8}}>{s.tasks.length} 项</span></h2><Link className="cp-link" style={{fontSize:12}} href="/compute-space/tasks">查看全部</Link></div><div className="cp-panel cp-table-wrap"><table className="cp-table"><thead><tr><th>任务名称 / 所属课题</th><th>工具</th><th>状态</th><th>最近更新</th><th/></tr></thead><tbody>{s.tasks.slice(0,4).map(t => <tr key={t.id}><td><Link href={`/compute-space/tasks/${t.id}`}>{t.name}</Link><div className="cp-muted" style={{fontSize:10,marginTop:4}}>{t.project}</div></td><td>{s.tools.find(v=>v.id===t.toolId)?.name.split(' ')[0]}</td><td><Status value={t.status}/>{t.status==='运行中' && <span className="cp-muted" style={{marginLeft:8}}>{t.progress}%</span>}</td><td className="cp-muted">{t.createdAt.slice(5,16)}</td><td><Link aria-label={`打开任务 ${t.name}`} href={`/compute-space/tasks/${t.id}`} className="cp-link"><ArrowUpRight size={16}/></Link></td></tr>)}</tbody></table></div></section>
    </div><aside className="cp-stack cp-home-aside"><Panel title={<span className="cp-row"><FlaskConical size={16}/>科研上下文</span>} actions={<button aria-label="添加科研上下文" className="cp-link" onClick={()=>setShowRefs(true)}><Plus size={16}/></button>}><div className="cp-context-item" style={{paddingTop:0}}><span>当前课题</span><strong style={{fontSize:13}}>{project.name}</strong></div><div className="cp-context-item"><span>科学假设 H1</span><p>温度与围压共同改变页岩裂缝破坏模式，热损伤影响其扩展路径。</p><Link href="/compute-space/handoff?direction=read" className="cp-link" style={{fontSize:11,display:'inline-block',marginTop:8}}>查看研究依据 <ChevronRight size={11} style={{display:'inline'}}/></Link></div><div className="cp-context-item"><span>已关联资源</span><div className="cp-row" style={{justifyContent:'space-between'}}><span className="cp-muted">科研数据</span><Link href="/compute-space/data" className="cp-link">{s.datasets.length} 个版本</Link></div><div className="cp-row" style={{justifyContent:'space-between',marginTop:9}}><span className="cp-muted">科研模型</span><Link href="/compute-space/models" className="cp-link">{s.models.length} 个版本</Link></div></div><div className="cp-note" style={{marginTop:14}}>计算方案、输入版本与研究证据将随任务保存，支持结果复现。</div></Panel><Panel title="从一个问题开始"><div className="cp-stack" style={{gap:0}}>{examples.map((e,i)=><button key={e} onClick={()=>setPrompt(e)} style={{textAlign:'left',fontSize:12,color:'#697586',lineHeight:1.9,padding:'12px 0',borderBottom:i===2?'none':'1px solid #edf0f3',display:'flex',gap:10}}><span style={{color:'#b0b6be',fontSize:11}}>0{i+1}</span><span>{e}</span><ChevronRight size={13} style={{flexShrink:0,marginTop:4}}/></button>)}</div></Panel></aside></div>
    <div className="cp-footer-note"><span className="cp-row"><Check size={12}/>方案先确认，计算可追溯，结果可验证</span><span>演示环境 · 数据与操作保存在当前浏览器</span></div>
    <Modal open={showRefs} onClose={()=>setShowRefs(false)} title="引用科研上下文" footer={<Button variant="primary" onClick={()=>setShowRefs(false)}>完成引用</Button>}><div className="cp-quick-actions" style={{marginTop:0,marginBottom:15}}>{Object.keys(refs).map(k=><button key={k} onClick={()=>setRefTab(k)} style={refTab===k?{color:'#b4232d',borderColor:'#b4232d'}:{}}>{k}</button>)}</div><div className="cp-stack">{refs[refTab].map(ref=><label key={ref} className="cp-row" style={{alignItems:'start',padding:12,border:'1px solid #e6e8ec',borderRadius:6}}><input type="checkbox" checked={s.references.includes(ref)} onChange={e=>e.target.checked?s.addReference(ref):s.removeReference(ref)}/><span style={{fontSize:13}}>{ref}</span></label>)}</div></Modal>
  </div>;
}

