import type { ComputePlan, ComputeTask } from './types';
type Subject = Pick<ComputePlan,'toolId'> & { title?: string; name?: string; method?: string; type?: string; goal?: string };
export function scenarioFor(subject: Subject){const text=`${subject.title||subject.name} ${subject.method||subject.type} ${subject.goal||''} ${subject.toolId}`;
  if(/合成生物|代谢|序列|cobra/i.test(text))return {kind:'bio',experiment:'代谢路径与产率验证实验',range:'诱导浓度 0.3–0.6 mM / 培养温度 30–34 ℃',sensitive:['诱导浓度','培养温度','培养时间'],conclusion:'模拟候选在相对产率、稳定性和代谢负担之间存在权衡，建议对排名靠前的路径进行独立培养与产率验证。',steps:['制备候选菌株与对照组','按诱导浓度、温度与时间设计平行培养','记录代谢通量、产率与生长状态','比较模拟结果与实测偏差'],outputs:['相对产率','代谢通量','生长稳定性']};
  if(!/页岩|裂缝|岩石/.test(text) && /材料|催化|Ni |Co |lammps/i.test(text))return {kind:'material',experiment:'催化材料热稳定性验证实验',range:'Ni 配比 20–40% / 焙烧温度 500–650 ℃',sensitive:['Ni 配比','Co 配比','焙烧温度'],conclusion:'模拟候选的热稳定性随组成与处理温度变化，需综合比较催化活性、稳定性及制备成本，并通过独立热分析确认。',steps:['按候选配比制备材料与空白对照','执行受控温度处理与热重分析','采集催化活性和循环稳定性指标','对比预测形成能与实测性能'],outputs:['热稳定性评分','形成能','催化活性']};
  if(/驱油|渗流|流体|openfoam/i.test(text))return {kind:'flow',experiment:'岩心驱替验证实验',range:'温度 60–120 ℃ / 注入压力 15–30 MPa',sensitive:['温度','注入压力','渗透率'],conclusion:'演示结果中注入压力与流体温度共同影响采收率，需要进行岩心驱替实验校验流动边界与残余饱和度。',steps:['准备标准岩心并测量孔渗参数','设置温压边界与注入速率','采集压力曲线与产出组分','对照模拟采收率及压力分布'],outputs:['驱替采收率','压降','饱和度分布']};
  if(/页岩|裂缝|岩石|有限元|XFEM|相场|comsol|abaqus/i.test(text))return {kind:'geo',experiment:'高温高压真三轴实验验证',range:'150–200 ℃ / 30–45 MPa',sensitive:['温度','围压','弹性模量'],conclusion:'演示计算结果：温度是主要敏感参数，围压影响次之。推荐 150–200 ℃、30–45 MPa 进行实验验证。',steps:['制备同岩性样品并记录弹性参数','按温度和围压组合稳定加载','采集应力曲线与 CT 裂缝表征','对照计算结果并记录误差与失败案例'],outputs:['裂缝扩展方向','最大主应力','塑性区范围']};
  return {kind:'generic',experiment:'科研结果对照验证',range:'沿用当前方案已确认的参数范围',sensitive:['方案主变量'],conclusion:'演示任务已完成配置与求解流程。请根据输出产物和目标指标开展人工分析，科学结论需独立验证。',steps:['检查输入与研究目标','按确认参数设置对照组','采集目标输出指标','分析误差并记录适用边界'],outputs:['目标指标','误差范围']};
}
export function scenarioPlan(goal: string):Partial<ComputePlan>{const scenario=scenarioFor({goal,toolId:''});if(scenario.kind==='material')return {method:'分子动力学与稳定性筛选',toolId:'lammps',datasetId:'data-catalyst-v1',modelId:'',hypothesis:'组成与制备温度共同影响催化材料的活性和热稳定性。',parameters:[{name:'Ni 配比',value:'30',unit:'%',source:'AI 推荐值 · 待确认'},{name:'Co 配比',value:'15',unit:'%',source:'领域默认值'},{name:'焙烧温度',value:'550',unit:'℃',source:'文献参数'}],outputs:scenario.outputs,risks:'模型适用范围受材料体系限制，预测性能需要独立实验确认。'};if(scenario.kind==='bio')return {method:'代谢通量分析',toolId:'cobra',datasetId:'data-bio-v1',modelId:'',hypothesis:'诱导浓度与培养温度影响代谢通量与目标产率。',parameters:[{name:'诱导浓度',value:'0.5',unit:'mM',source:'AI 推荐值 · 待确认'},{name:'培养温度',value:'32',unit:'℃',source:'领域默认值'},{name:'培养时间',value:'48',unit:'h',source:'实验参数'}],outputs:scenario.outputs,risks:'代谢约束和生长状态需通过实验验证。'};return {};}
export function taskScenario(task:ComputeTask){return scenarioFor({name:task.name,toolId:task.toolId,type:task.type});}

