'use client';

import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { Suspense, useEffect, useMemo, useState } from 'react';
import { Activity, ArrowLeft, ArrowRight, Check, CheckCircle2, ChevronRight, Clock3, Cpu, Database, Download, FileCode2, FileImage, FileJson, FileText, FlaskConical, FolderOpen, GitBranch, GitCompareArrows, Info, Layers3, ListFilter, MoreHorizontal, Pause, Play, Plus, RotateCcw, Search, ShieldCheck, SlidersHorizontal, Sparkles, Square, Terminal, TriangleAlert, X } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useComputeStore } from './store';
import type { ComputeTask, Parameter, TaskStatus } from './types';
import { Button, Empty, Modal, PageHeader, Panel, Status, Tabs, downloadFile } from './ui';
import { TaskAnalysis, taskMetrics, resultSchema, resultConclusion } from './analysis';
import styles from './tasks.module.css';

const NORMAL_STATES: TaskStatus[] = ['草稿', '待确认', '待提交', '排队中', '运行中', '结果生成中', '已完成'];
const EXCEPTION_STATES: TaskStatus[] = ['暂停', '失败', '取消', '资源不足', '等待人工处理'];
const ACTIVE_STATES: TaskStatus[] = ['排队中', '运行中', '结果生成中'];
const DETAIL_TABS = ['概览', '参数', '输入', '运行', '日志', '结果', '分析', '版本与追溯'];
const nextLabel: Partial<Record<TaskStatus, string>> = { 草稿: '提交确认', 待确认: '确认计算配置', 待提交: '提交计算任务', 排队中: '分配资源并运行', 运行中: '推进计算演示', 结果生成中: '生成计算结果', 暂停: '恢复运行', 等待人工处理: '继续处理' };

function formatTime(value: string) { return value.replace('T', ' ').slice(0, 16); }
function taskManifest(task: ComputeTask) { return JSON.stringify({ ...task, conclusion: resultSchema(task).domain !== 'generic' ? resultConclusion(task) : '此演示未配置该领域的结果指标；参见人工评价与分析待办。', simulation: true, exportedAt: new Date().toISOString(), scientificBoundary: '演示数据；结果解释需人工与实验验证。' }, null, 2); }
function downloadResults(task: ComputeTask) { const supported = resultSchema(task).domain !== 'generic'; downloadFile(`${task.id}-计算结果.json`, JSON.stringify({ task: JSON.parse(taskManifest(task)), metricSchema: resultSchema(task), metrics: supported ? taskMetrics(task) : null, result: supported ? task.conclusion : '此演示未配置该领域的结果指标。仅保留通用任务包、参数和来源。', review: task.review }, null, 2), 'application/json'); }

function Progress({ value, status }: { value: number; status: string }) {
  return <div className={styles.progressCell}><div className={styles.progressTrack}><i style={{ width: `${Math.max(0, Math.min(100, value))}%`, background: status === '失败' ? '#c64135' : status === '已完成' ? '#398578' : undefined }} /></div><span>{value}%</span></div>;
}

export function TaskCenter() {
  const router = useRouter();
  const { tasks, tools, datasets, plans, updateTask, retryTask, cloneTask } = useComputeStore();
  const [search, setSearch] = useState('');
  const [tab, setTab] = useState('全部任务');
  const [advanced, setAdvanced] = useState(false);
  const [type, setType] = useState('全部类型');
  const [project, setProject] = useState('全部课题');
  const [tool, setTool] = useState('全部工具');
  const [status, setStatus] = useState('全部状态');
  const [creator, setCreator] = useState('全部创建人');
  const [start, setStart] = useState('');
  const [end, setEnd] = useState('');
  const [hasResult, setHasResult] = useState(false);
  const [onlyErrors, setOnlyErrors] = useState(false);
  const [selected, setSelected] = useState<string[]>([]);
  const [modal, setModal] = useState<{ action: 'stop' | 'retry'; task: ComputeTask } | null>(null);
  const [resource, setResource] = useState('');
  const [message, setMessage] = useState('');
  const active = tasks.filter((task) => ACTIVE_STATES.includes(task.status));
  const completed = tasks.filter((task) => task.status === '已完成');
  const exceptions = tasks.filter((task) => ['失败', '资源不足', '等待人工处理'].includes(task.status));
  const shown = useMemo(() => tasks.filter((task) => {
    const nameMatch = `${task.name} ${task.id} ${task.project}`.toLowerCase().includes(search.toLowerCase());
    const tabMatch = tab === '全部任务' || (tab === '进行中' && ACTIVE_STATES.includes(task.status)) || (tab === '已完成' && task.status === '已完成') || (tab === '需要关注' && EXCEPTION_STATES.includes(task.status)) || (tab === '草稿' && ['草稿', '待确认', '待提交'].includes(task.status));
    return nameMatch && tabMatch && (type === '全部类型' || task.type === type) && (project === '全部课题' || task.project === project) && (tool === '全部工具' || task.toolId === tool) && (status === '全部状态' || task.status === status) && (creator === '全部创建人' || task.creator === creator) && (!start || task.createdAt.slice(0, 10) >= start) && (!end || task.createdAt.slice(0, 10) <= end) && (!onlyErrors || EXCEPTION_STATES.includes(task.status)) && (!hasResult || task.resultCount > 0);
  }), [tasks, search, tab, type, project, tool, status, creator, start, end, onlyErrors, hasResult]);
  const filtersActive = type !== '全部类型' || project !== '全部课题' || tool !== '全部工具' || status !== '全部状态' || creator !== '全部创建人' || start || end || hasResult || onlyErrors;

  function resetFilters() { setSearch(''); setTab('全部任务'); setType('全部类型'); setProject('全部课题'); setTool('全部工具'); setStatus('全部状态'); setCreator('全部创建人'); setStart(''); setEnd(''); setHasResult(false); setOnlyErrors(false); }
  function command(task: ComputeTask, action: string) {
    if (action === 'retry') { const selectedTool = tools.find((item) => item.id === task.toolId); if (!selectedTool || selectedTool.status !== '已上架' || /过期|不可用/.test(selectedTool.license)) { setMessage('无法重试：工具未上架或许可证不可用。请先在科研工具工作台恢复工具可用状态。'); return; } }
    if (action === 'resume') { updateTask(task.id, { status: '运行中', logs: [...task.logs, '[INFO] 用户恢复计算，读取最近检查点。'] }); setMessage('已从最近检查点恢复运行。'); return; }
    if (action === 'stop' || action === 'retry') { setModal({ action, task }); setResource(task.resources.includes('128') ? task.resources.replace('128', '256') : `${task.resources} · 内存 256 GB`); }
    if (action === 'clone' || action === 'version') {
      const id = cloneTask(task.id);
      if (action === 'version') updateTask(id, { name: task.name, version: task.version + 1, parentId: task.id });
      router.push(`/compute-space/tasks/${id}`);
    }
    if (action === 'download') downloadResults(task);
  }
  function compareSelected() { const valid = selected.filter((id) => tasks.some((task) => task.id === id && task.status === '已完成')); if (valid.length < 2 || valid.length > 4) { setMessage('请勾选 2–4 个已完成的任务进行结果对比。'); return; } const selectedTasks = tasks.filter((task) => valid.includes(task.id)); if (selectedTasks.some((task) => resultSchema(task).domain === 'generic') || new Set(selectedTasks.map((task) => resultSchema(task).domain)).size > 1 || new Set(selectedTasks.map((task) => task.project)).size > 1) { setMessage('请选择同一课题与同一领域的已完成任务进行结果对比。'); return; } router.push(`/compute-space/analysis?tasks=${valid.join(',')}`); }

  return <div data-prd-id="REQ-TASK-001">
    <PageHeader title="计算任务" description="掌握每一次计算的进展，让方案、执行与结果完整连接。" actions={<><Link className={styles.secondaryLink} href="/compute-space/analysis"><GitCompareArrows size={16} /> 结果对比</Link><Link className={styles.primaryLink} href="/compute-space/agent"><Plus size={17} /> 新建计算任务</Link></>} />
    <div className={styles.taskStats}>
      <button onClick={() => setTab('全部任务')}><div className={styles.statIcon}><Layers3 size={19} /></div><span>全部计算任务<strong>{tasks.length}<small>个</small></strong></span><span className={styles.statSub}>覆盖 {new Set(tasks.map((task) => task.project)).size} 个研究课题</span></button>
      <button onClick={() => setTab('进行中')}><div className={`${styles.statIcon} ${styles.liveIcon}`}><Activity size={19} /></div><span>正在计算<strong>{active.length}<small>个</small></strong></span><span className={styles.statSub}><i className={styles.liveDot} /> 资源正常运行</span></button>
      <button onClick={() => setTab('已完成')}><div className={`${styles.statIcon} ${styles.doneIcon}`}><CheckCircle2 size={19} /></div><span>已生成结果<strong>{completed.length}<small>个</small></strong></span><span className={styles.statSub}>等待分析与科学发现</span></button>
      <button onClick={() => setTab('需要关注')}><div className={`${styles.statIcon} ${styles.warningIcon}`}><TriangleAlert size={19} /></div><span>需要关注<strong>{exceptions.length}<small>个</small></strong></span><span className={styles.statSub}>异常诊断与恢复</span></button>
    </div>
    {message && <div className="cp-note" role="status">{message}<button className={styles.inlineClose} onClick={() => setMessage('')} aria-label="关闭提示"><X size={14} /></button></div>}
    <Panel>
      <div className={styles.listToolbar}><Tabs items={['全部任务', '进行中', '已完成', '需要关注', '草稿']} value={tab} onChange={setTab} /><div className="cp-row"><div className={styles.search}><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="搜索任务名称、编号、课题" aria-label="搜索计算任务" /></div><Button variant="secondary" onClick={() => setAdvanced(!advanced)}><ListFilter size={16} /> 筛选{filtersActive ? ' · 已启用' : ''}</Button></div></div>
      {advanced && <div className={styles.filterArea}><div className={styles.filterGrid}>
        <label className="cp-field">任务类型<select className="cp-select" value={type} onChange={(event) => setType(event.target.value)}><option>全部类型</option>{Array.from(new Set(tasks.map((task) => task.type))).map((value) => <option key={value}>{value}</option>)}</select></label>
        <label className="cp-field">所属课题<select className="cp-select" value={project} onChange={(event) => setProject(event.target.value)}><option>全部课题</option>{Array.from(new Set(tasks.map((task) => task.project))).map((value) => <option key={value}>{value}</option>)}</select></label>
        <label className="cp-field">工具 / 软件<select className="cp-select" value={tool} onChange={(event) => setTool(event.target.value)}><option>全部工具</option>{tools.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
        <label className="cp-field">任务状态<select className="cp-select" value={status} onChange={(event) => setStatus(event.target.value)}><option>全部状态</option>{[...NORMAL_STATES, ...EXCEPTION_STATES].map((value) => <option key={value}>{value}</option>)}</select></label>
        <label className="cp-field">创建人<select className="cp-select" value={creator} onChange={(event) => setCreator(event.target.value)}><option>全部创建人</option>{Array.from(new Set(tasks.map((task) => task.creator))).map((value) => <option key={value}>{value}</option>)}</select></label>
        <label className="cp-field">开始日期<input className="cp-input" type="date" value={start} onChange={(event) => setStart(event.target.value)} /></label><label className="cp-field">结束日期<input className="cp-input" type="date" min={start} value={end} onChange={(event) => setEnd(event.target.value)} /></label>
      </div><div className={styles.filterFooter}><label><input type="checkbox" checked={onlyErrors} onChange={(event) => setOnlyErrors(event.target.checked)} /> 仅看异常任务</label><label><input type="checkbox" checked={hasResult} onChange={(event) => setHasResult(event.target.checked)} /> 已生成结果</label><Button variant="ghost" onClick={resetFilters}>重置筛选</Button></div></div>}
      {selected.length > 0 && <div className={styles.batchBar}><span>已选择 <strong>{selected.length}</strong> 个任务</span><Button variant="secondary" onClick={compareSelected}><GitCompareArrows size={15} /> 对比结果</Button><Button variant="ghost" onClick={() => setSelected([])}>取消选择</Button></div>}
      <div className="cp-table-wrap"><table className={`cp-table ${styles.taskTable}`}><thead><tr><th><input type="checkbox" aria-label="选择所有可对比任务" checked={shown.some((task) => task.status === '已完成') && shown.filter((task) => task.status === '已完成').every((task) => selected.includes(task.id))} onChange={(event) => setSelected(event.target.checked ? shown.filter((task) => task.status === '已完成').map((task) => task.id) : [])} /></th><th>任务名称 / 类型</th><th>状态</th><th>进度</th><th>工具 / 数据版本</th><th>资源</th><th>创建时间 / 耗时</th><th>结果</th><th>操作</th></tr></thead><tbody>{shown.map((task) => <tr key={task.id}><td><input type="checkbox" aria-label={`选择 ${task.name}`} checked={selected.includes(task.id)} disabled={task.status !== '已完成'} onChange={(event) => setSelected((current) => event.target.checked ? [...current, task.id] : current.filter((id) => id !== task.id))} /></td><td><Link className={styles.taskName} href={`/compute-space/tasks/${task.id}`}>{task.name}<ChevronRight size={13} /></Link><div className={styles.tableSub}>{task.type}<span>·</span>{task.project}</div><div className={styles.tableSub}>{task.id}<span>·</span>方案 {plans.find((plan) => plan.id === task.planId)?.title || task.planId}</div></td><td><Status value={task.status} /></td><td><Progress value={task.progress} status={task.status} /></td><td>{tools.find((item) => item.id === task.toolId)?.name || task.toolId}<div className={styles.tableSub}>{datasets.find((item) => item.id === task.datasetId)?.name || task.datasetId} · V{datasets.find((item) => item.id === task.datasetId)?.version || 1}</div></td><td><span className={styles.resourceCell}>{task.resources}</span></td><td>{task.createdAt.slice(0, 10)}<div className={styles.tableSub}><Clock3 size={11} />{task.duration}<span>·</span>{task.creator}</div></td><td>{task.resultCount > 0 ? <Link href={`/compute-space/tasks/${task.id}?tab=结果`} className="cp-link">{task.resultCount} 项</Link> : <span className="cp-muted">—</span>}</td><td><div className={styles.rowActions}><Link href={`/compute-space/tasks/${task.id}`} title="查看详情" aria-label={`查看 ${task.name} 的详情`}><FolderOpen size={16} /></Link><Link href={`/compute-space/tasks/${task.id}?tab=日志`} title="查看日志" aria-label={`查看 ${task.name} 的日志`}><Terminal size={16} /></Link><label className={styles.moreSelect}><MoreHorizontal size={18} /><select aria-label={`${task.name} 的更多操作`} value="" onChange={(event) => command(task, event.target.value)}><option value="" disabled>更多操作</option>{ACTIVE_STATES.includes(task.status) && <option value="stop">停止任务</option>}{EXCEPTION_STATES.includes(task.status) && task.status !== '暂停' && <option value="retry">修改后重试</option>}{task.status === '暂停' && <option value="resume">恢复运行</option>}<option value="clone">克隆任务</option><option value="version">创建新版本</option>{task.status === '已完成' && <><option value="clone">重新运行</option><option value="download">下载结果</option></>}</select></label></div></td></tr>)}</tbody></table></div>
      {!shown.length && <Empty title="没有符合条件的任务" description="调整搜索词或筛选条件，查看其他计算任务。" action={<Button variant="secondary" onClick={resetFilters}>重置筛选</Button>} />}
      <div className={styles.tableFooter}><span>共 {shown.length} 个任务</span><span><ShieldCheck size={13} /> 所有计算均保留方案、数据与版本追溯</span></div>
    </Panel>
    <Modal open={!!modal} onClose={() => setModal(null)} title={modal?.action === 'stop' ? '停止计算任务' : '修改资源后重试'} footer={<><Button variant="secondary" onClick={() => setModal(null)}>取消</Button><Button variant={modal?.action === 'stop' ? 'danger' : 'primary'} disabled={modal?.action === 'retry' && !resource.trim()} onClick={() => { if (!modal) return; if (modal.action === 'stop') updateTask(modal.task.id, { status: '取消', logs: [...modal.task.logs, `[${new Date().toLocaleTimeString('zh-CN')}] [WARNING] 用户停止任务，释放计算资源。`] }); else { updateTask(modal.task.id, { resources: resource }); retryTask(modal.task.id); } setMessage(modal.action === 'stop' ? '任务已停止，日志与配置已保留。' : '已按更新后的配置提交重试，可在任务详情查看进度。'); setModal(null); }}>{modal?.action === 'stop' ? '确认停止' : '确认重试'}</Button></>}>
      <p><strong>{modal?.task.name}</strong></p>{modal?.action === 'stop' ? <p className="cp-muted">停止后将释放资源，未完成的计算结果不作为有效产物。配置和完整日志仍可追溯。</p> : <><div className="cp-alert">阶段：求解阶段<br />原因：{modal?.task.error || '任务执行中断'}<br />影响：本次未完成的计算结果无效。</div><label className="cp-field">计算资源<input className="cp-input" value={resource} onChange={(event) => setResource(event.target.value)} /></label><p className="cp-muted">建议增加内存，或进入任务详情减小网格规模后重试。</p></>}
    </Modal>
  </div>;
}

function ResourceCharts({ task }: { task: ComputeTask }) {
  const factor = task.status === '运行中' ? 1 : task.status === '已完成' ? .86 : .28;
  const data = Array.from({ length: 12 }, (_, i) => ({ time: `${Math.floor(i / 3) + 10}:${String((i % 3) * 20).padStart(2, '0')}`, cpu: Math.round((38 + i * 3.7 + Math.sin(i) * 9) * factor), gpu: Math.round((48 + i * 3.3 + Math.sin(i * 1.7) * 8) * factor), memory: Math.round((45 + i * 4 + Math.sin(i) * 6) * factor), io: Math.round((75 + i * 20 + Math.sin(i) * 50) * factor) }));
  return <div className={styles.resourceCharts}>{[{ key: 'cpu', label: 'CPU 使用率', unit: '%', color: '#ce4c36' }, { key: 'gpu', label: 'GPU 使用率', unit: '%', color: '#377e84' }, { key: 'memory', label: '内存使用', unit: 'GB', color: '#75629b' }, { key: 'io', label: '存储 I/O', unit: 'MB/s', color: '#bd8b3c' }].map(({ key, label, unit, color }) => <div key={key} className={styles.resourceChart}><div><span>{label}</span><strong>{data[data.length - 1][key as 'cpu' | 'gpu' | 'memory' | 'io']}<small>{unit}</small></strong></div><ResponsiveContainer width="100%" height={115}><AreaChart data={data} margin={{ left: -32, top: 4, right: 3 }}><defs><linearGradient id={`resource-${key}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity={.16} /><stop offset="100%" stopColor={color} stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#eff0ef" vertical={false} /><XAxis dataKey="time" interval={5} tick={{ fontSize: 9 }} tickLine={false} axisLine={false} /><YAxis tick={{ fontSize: 9 }} tickLine={false} axisLine={false} domain={key === 'cpu' || key === 'gpu' ? [0, 100] : [0, 'auto']} /><Tooltip /><Area dataKey={key} name={label} stroke={color} strokeWidth={1.8} fill={`url(#resource-${key})`} /></AreaChart></ResponsiveContainer></div>)}</div>;
}

function MeshPreview() {
  return <svg viewBox="0 0 330 238" role="img" aria-label="演示计算结果：三维应力场，颜色代表相对应力值" className={styles.mesh}>
    <defs><linearGradient id="mesh-front" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#215f9c" /><stop offset=".35" stopColor="#329aad" /><stop offset=".65" stopColor="#a6c662" /><stop offset="1" stopColor="#d97b40" /></linearGradient><linearGradient id="mesh-top"><stop stopColor="#347fb2" /><stop offset=".7" stopColor="#97bb68" /><stop offset="1" stopColor="#d69545" /></linearGradient><linearGradient id="mesh-right" x1="0" x2="1" y1="1" y2="0"><stop stopColor="#2966a0" /><stop offset=".5" stopColor="#4daeb4" /><stop offset="1" stopColor="#b9c651" /></linearGradient><linearGradient id="mesh-scale" x1="0" x2="0" y1="1" y2="0"><stop stopColor="#215f9c" /><stop offset=".35" stopColor="#329aad" /><stop offset=".6" stopColor="#a6c662" /><stop offset="1" stopColor="#d95c3d" /></linearGradient></defs>
    <ellipse cx="149" cy="214" rx="96" ry="10" fill="#dfe5e1" opacity=".5" /><path d="M66 73 155 37 240 71 150 112Z" fill="url(#mesh-top)" stroke="#3d798d" /><path d="M66 73 150 112 150 209 66 167Z" fill="url(#mesh-front)" stroke="#337c8b" /><path d="M150 112 240 71 240 166 150 209Z" fill="url(#mesh-right)" stroke="#317b8d" />
    {Array.from({ length: 6 }, (_, i) => <g key={i} stroke="#183f65" strokeWidth=".5" opacity=".45"><path d={`M${66 + i * 14} ${73 + i * 6.5}V${167 + i * 7}`} /><path d={`M66 ${73 + i * 16}L150 ${112 + i * 16}`} /><path d={`M${150 + i * 15} ${112 - i * 6.8}V${209 - i * 7.1}`} /><path d={`M150 ${112 + i * 16}L240 ${71 + i * 16}`} /><path d={`M${66 + i * 15} ${73 - i * 6}L${150 + i * 15} ${112 - i * 6.8}`} /><path d={`M${66 + i * 14} ${73 + i * 6.5}L${155 + i * 14} ${37 + i * 5.7}`} /></g>)}
    <path d="M113 57 125 72 107 90 125 106 108 128 134 146 115 170 144 195" stroke="#ba482f" strokeWidth="4" fill="none" opacity=".85" /><path d="M111 56 123 73 105 90 122 106 106 128 131 146 113 170 141 195" stroke="#f8d49b" strokeWidth="1.6" fill="none" />
    <rect x="277" y="73" width="8" height="107" rx="2" fill="url(#mesh-scale)" /><g fill="#6d7682" fontSize="9"><text x="272" y="57">应力 / MPa</text><text x="290" y="80">80</text><text x="290" y="132">40</text><text x="290" y="182">0</text><text x="34" y="208">X</text><text x="77" y="225">Y</text><text x="40" y="174">Z</text></g><path d="M47 213 29 199M47 213 73 219M47 213V182" stroke="#81928c" fill="none" />
  </svg>;
}

function DomainPreview({ task }: { task: ComputeTask }) {
  const schema = resultSchema(task);
  if (schema.domain === 'fracture') return <MeshPreview />;
  const metrics = taskMetrics(task);
  const curve = Array.from({ length: 17 }, (_, index) => `${44 + index * 13},${176 - 105 * (1 - Math.exp(-index / 5)) / (1 - Math.exp(-16 / 5))}`).join(' ');
  return <svg viewBox="0 0 330 238" role="img" aria-label={`${schema.primary}演示曲线`} className={styles.mesh}><rect x="30" y="44" width="269" height="148" rx="6" fill="#fff" />{[0, 1, 2, 3].map((line) => <line key={line} x1="44" x2="279" y1={71 + line * 35} y2={71 + line * 35} stroke="#e9eeeb" strokeDasharray="3 3" />)}<polyline points={curve} fill="none" stroke="#ce4c36" strokeWidth="2.6" /><circle cx="252" cy="71" r="4" fill="#ce4c36" /><g fontFamily="sans-serif"><text x="43" y="30" fontSize="11" fill="#6c7b76">{schema.curve} / {schema.unit}</text><text x="211" y="58" fontSize="17" fontWeight="600" fill="#ba5a43">{metrics.length}</text><text x="45" y="211" fontSize="9" fill="#93a29b">0%</text><text x="230" y="211" fontSize="9" fill="#93a29b">100% 模拟进度</text><text x="44" y="230" fontSize="9" fill="#93a29b">确定性演示计算 · 待独立实验验证</text></g></svg>;
}

function LogViewer({ task }: { task: ComputeTask }) {
  const [mode, setMode] = useState('实时日志');
  const [level, setLevel] = useState('全部级别');
  const [search, setSearch] = useState('');
  const [explained, setExplained] = useState(false);
  const lines = task.logs.filter((line) => (level === '全部级别' || (level === '关键日志' ? /ERROR|WARNING|完成|启动|确认|提交|重试|人工/.test(line) : line.includes(level))) && line.toLowerCase().includes(search.toLowerCase()));
  return <div className="cp-stack"><Panel title="运行日志" actions={<Button variant="secondary" onClick={() => downloadFile(`${task.id}.log`, task.logs.join('\n'), 'text/plain;charset=utf-8')}><Download size={15} /> 下载完整日志</Button>}><div className={styles.logToolbar}><Tabs items={['实时日志', '历史日志']} value={mode} onChange={setMode} /><div className="cp-row"><select className="cp-select" aria-label="日志级别" value={level} onChange={(event) => setLevel(event.target.value)}>{['全部级别', '关键日志', 'INFO', 'WARNING', 'ERROR'].map((item) => <option key={item}>{item}</option>)}</select><div className={styles.search}><Search size={15} /><input aria-label="搜索日志" placeholder="搜索日志内容" value={search} onChange={(event) => setSearch(event.target.value)} /></div></div></div><div className={styles.terminal}><div className={styles.terminalHead}><span><i /><i /><i />{task.id} / solver.log</span><small>{mode === '实时日志' && ACTIVE_STATES.includes(task.status) ? '随任务推进更新' : '已保存的完整记录'}</small></div><div className={styles.logLines} role="log" aria-label="任务日志">{lines.length ? lines.map((line, i) => <div key={`${i}-${line}`} className={line.includes('ERROR') ? styles.errorLog : line.includes('WARNING') ? styles.warningLog : ''}><span>{String(i + 1).padStart(3, '0')}</span><code>{line}</code></div>) : <p className={styles.noLogs}>没有匹配的日志。请调整级别或搜索条件。</p>}</div><div className={styles.terminalFooter}><span>{lines.length} / {task.logs.length} 行</span><span>UTF-8 · {mode === '实时日志' ? '任务状态同步' : `任务版本 V${task.version}`}</span></div></div><div className={styles.logFooter}><p>完整日志是排查依据；Agent 解释可帮助定位问题。</p><Button variant="secondary" onClick={() => setExplained(!explained)}><Sparkles size={15} />{explained ? '收起异常解释' : '让 AI 解释异常'}</Button></div></Panel>{explained && <Panel title="异常解释与处理建议" actions={<Status value="待人工分析" />}><div className="cp-note">{task.error ? `日志显示：${task.error}。异常发生在求解阶段，当前未完成产物不可作为有效结果。` : '当前完整日志未记录阻断性错误。若有收敛警告，请检查迭代次数与残差阈值。'}</div><div className={styles.explainGrid}><div><strong>可能原因</strong><p>问题规模增长导致峰值内存需求升高；并行进程数量与可用内存不匹配。</p></div><div><strong>建议操作</strong><p>将内存提升至 256 GB，或降低问题规模；保留原配置后创建新版本验证。</p></div><div><strong>验证方式</strong><p>重试后对照完整日志，检查残差收敛和网格无关性。解释来自演示诊断规则。</p></div></div></Panel>}</div>;
}

function GenericResultFiles({ task, onAsset }: { task: ComputeTask; onAsset: (name: string) => void }) {
  const [preview, setPreview] = useState<string | null>(null);
  const escape = (text: string) => `"${text.replaceAll('"', '""')}"`;
  const files = [
    { name: '任务结果说明.md', type: '结果状态', content: `# ${task.name}\n\n任务：${task.id} / V${task.version}\n\n此演示未配置该领域的结果指标。当前产物为通用任务配置、参数、运行日志与来源包，不包含定量科学结论。\n\n评价状态：${task.review || '待人工分析'}` },
    { name: '完整任务清单.json', type: '任务清单', content: taskManifest({ ...task, conclusion: '此演示未配置该领域的结果指标。' }) },
    { name: '输入参数.csv', type: '参数表格', content: '\uFEFF参数,值,单位,来源\n' + task.parameters.map((p) => [p.name, p.value, p.unit, p.source].map(escape).join(',')).join('\n') },
    { name: '运行日志.log', type: '日志', content: task.logs.join('\n') },
    { name: '运行环境.json', type: '环境配置', content: JSON.stringify({ tool: task.toolId, toolVersion: task.toolVersion, environment: task.environment, resources: task.resources, queue: task.queue }, null, 2) },
    { name: '输入来源.json', type: '来源引用', content: JSON.stringify({ plan: task.planId, snapshot: task.planSnapshot, dataset: task.datasetId, model: task.modelId, parent: task.parentId }, null, 2) },
    { name: '分析待办.md', type: '分析说明', content: '# 待完成的领域分析\n\n- 配置本领域的定量评价指标\n- 导入真实求解结果与参考基准\n- 进行误差与异常分析\n- 人工确认适用边界\n- 与独立实验结果比较' },
  ];
  const current = files.find((file) => file.name === preview);
  const mime = (name: string) => name.endsWith('.json') ? 'application/json' : name.endsWith('.csv') ? 'text/csv;charset=utf-8' : 'text/plain;charset=utf-8';
  if (task.status !== '已完成') return <Empty title="结果包尚未生成" description="任务完成后可查看通用求解记录、输入参数与来源清单。" />;
  return <div className="cp-stack"><div className="cp-note"><Info size={17} />此演示未配置该领域的结果指标。以下文件保留计算流程和来源，不包含未验证的定量结论。</div><Panel title="通用计算结果包" actions={<Button variant="secondary" onClick={() => downloadResults(task)}><Download size={15} />导出任务包</Button>}><div className="cp-table-wrap"><table className="cp-table"><thead><tr><th>文件</th><th>产物类型</th><th>来源</th><th>操作</th></tr></thead><tbody>{files.map((file) => <tr key={file.name}><td><div className={styles.fileName}><FileText size={18} /><button onClick={() => setPreview(file.name)}>{file.name}</button></div></td><td>{file.type}</td><td className="cp-muted">{task.id} · V{task.version}</td><td><div className="cp-row"><Button variant="ghost" onClick={() => setPreview(file.name)}>预览</Button><Button variant="ghost" onClick={() => downloadFile(`${task.id}-${file.name}`, file.content, mime(file.name))}>下载</Button><Button variant="ghost" onClick={() => onAsset(file.name)}>加入 Artifact</Button></div></td></tr>)}</tbody></table></div></Panel><Modal open={!!current} onClose={() => setPreview(null)} title={current?.name || '产物预览'} footer={<><Button onClick={() => setPreview(null)}>关闭</Button><Button variant="primary" onClick={() => current && downloadFile(current.name, current.content, mime(current.name))}>下载文件</Button></>}><pre className={styles.filePreview}>{current?.content}</pre></Modal></div>;
}

function ResultFiles({ task, onAsset }: { task: ComputeTask; onAsset: (name: string) => void }) {
  if (resultSchema(task).domain === 'generic') return <GenericResultFiles task={task} onAsset={onAsset} />;
  return <FractureResultFiles task={task} onAsset={onAsset} />;
}

function FractureResultFiles({ task, onAsset }: { task: ComputeTask; onAsset: (name: string) => void }) {
  const [preview, setPreview] = useState<string | null>(null);
  const metric = taskMetrics(task); const schema = resultSchema(task);
  const csv = `模拟进度,${schema.primary}_${schema.unit},${schema.secondary}_${schema.secondaryUnit}\n${Array.from({ length: 11 }, (_, i) => `${i * 10},${(metric.length * i / 10).toFixed(2)},${(metric.stress * i / 10).toFixed(2)}`).join('\n')}`;
  const report = `# ${task.name}\n\n任务：${task.id} / V${task.version}\n\n## 指标摘要\n- ${schema.primary}：${metric.length} ${schema.unit}\n- ${schema.secondary}：${metric.stress} ${schema.secondaryUnit}\n- ${schema.third}：${metric.quality} ${schema.thirdUnit}\n- 相对误差：${metric.error}%\n\n## 计算观察\n${resultConclusion(task)}\n\n## 可信性状态\n${task.review || '待人工分析'}\n\n演示计算结果，不能直接作为科学结论。`;
  const svg = schema.domain === 'fracture' ? `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="400"><rect width="640" height="400" fill="#fff"/><text x="40" y="35" font-family="sans-serif" font-size="18">AI4S · 示意应力场 / MPa</text>${Array.from({ length: 100 }, (_, i) => { const x = i % 10; const y = Math.floor(i / 10); return `<rect x="${50 + x * 32}" y="${60 + y * 28}" width="32" height="28" fill="hsl(${210 - (x + y) * 10},55%,50%)" stroke="#fff" stroke-width=".5"/>`; }).join('')}<text x="410" y="120" font-family="sans-serif" font-size="13">演示结果 · 需人工评价</text><text x="410" y="150" font-family="sans-serif" font-size="13">最大应力 ${metric.stress} MPa</text></svg>` : `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="360"><rect width="640" height="360" fill="#fff"/><text x="40" y="42" font-family="sans-serif" font-size="18">${schema.primary} · 演示结果</text><path d="M50 260 C120 180 180 110 300 80 S440 60 540 60" fill="none" stroke="#ce4c36" stroke-width="4"/><text x="45" y="303" font-family="sans-serif" font-size="14">${schema.primary}: ${metric.length} ${schema.unit} / ${schema.secondary}: ${metric.stress} ${schema.secondaryUnit}</text><text x="45" y="332" font-family="sans-serif" font-size="12">${schema.third}: ${metric.quality} ${schema.thirdUnit} · 待人工与实验验证</text></svg>`;
  const files = [
    { name: '计算结果摘要.md', type: '结果摘要', icon: FileText, content: report, mime: 'text/markdown;charset=utf-8' },
    { name: schema.curve + '.csv', type: '曲线 / 表格', icon: FileCode2, content: csv, mime: 'text/csv;charset=utf-8' },
    { name: '关键指标.json', type: '指标', icon: FileJson, content: JSON.stringify({ scenario: schema.domain, metrics: [{ name: schema.primary, value: metric.length, unit: schema.unit }, { name: schema.secondary, value: metric.stress, unit: schema.secondaryUnit }, { name: schema.third, value: metric.quality, unit: schema.thirdUnit }], relativeErrorPercent: metric.error, parameters: task.parameters, demonstration: true }, null, 2), mime: 'application/json' },
    { name: schema.primary + '示意图.svg', type: '结果图片', icon: FileImage, content: svg, mime: 'image/svg+xml' },
    { name: '模型配置.json', type: '模型配置', icon: FileCode2, content: JSON.stringify({ task: task.id, model: task.modelId, tool: task.toolId, version: task.toolVersion, parameters: task.parameters, demonstration: true }, null, 2), mime: 'application/json' },
    { name: '计算分析报告.md', type: '研究报告', icon: FileText, content: `${report}\n\n## 下一步\n开展${schema.next}，对比计算预测与实测结果。`, mime: 'text/markdown;charset=utf-8' },
    { name: '任务追溯清单.json', type: '追溯清单', icon: GitBranch, content: taskManifest(task), mime: 'application/json' },
  ];
  const file = files.find((item) => item.name === preview);
  if (task.status !== '已完成') return <Empty title="计算结果尚未生成" description="完成求解与结果生成阶段后，文件、指标、图表和报告将统一展示在这里。" />;
  return <div className="cp-stack"><div className={styles.resultHero}><div className={styles.resultVisual}><DomainPreview task={task} /><span>{schema.primary} · 演示结果</span></div><div className={styles.resultSummary}><span className={styles.successEyebrow}><CheckCircle2 size={15} />计算结果已生成</span><h3>从计算产物中，发现下一步研究线索</h3><p>{resultConclusion(task)}</p><div className={styles.resultMetrics}><div><span>{schema.primary}</span><strong>{metric.length}<small>{schema.unit}</small></strong></div><div><span>{schema.secondary}</span><strong>{metric.stress}<small>{schema.secondaryUnit}</small></strong></div><div><span>{schema.third}</span><strong>{metric.quality}<small>{schema.thirdUnit}</small></strong></div></div><div className="cp-row"><Status value={task.review || '待人工分析'} /><Link className="cp-link" href={`/compute-space/analysis?tasks=${task.id}`}>进入结果分析 <ArrowRight size={14} /></Link></div></div></div><Panel title="结果文件" actions={<Button variant="secondary" onClick={() => downloadResults(task)}><Download size={15} /> 导出结果数据包</Button>}><div className="cp-table-wrap"><table className="cp-table"><thead><tr><th>文件名称</th><th>类型</th><th>来源</th><th>操作</th></tr></thead><tbody>{files.map((item) => <tr key={item.name}><td><div className={styles.fileName}><item.icon size={19} /><button onClick={() => setPreview(item.name)}>{item.name}</button></div></td><td>{item.type}</td><td className="cp-muted">{task.id} · V{task.version}</td><td><div className="cp-row"><Button variant="ghost" onClick={() => setPreview(item.name)}>预览</Button><Button variant="ghost" onClick={() => downloadFile(`${task.id}-${item.name}`, item.content, item.mime)}><Download size={14} />下载</Button><Button variant="ghost" onClick={() => onAsset(item.name)}>加入 Artifact</Button></div></td></tr>)}</tbody></table></div></Panel><Modal open={!!file} onClose={() => setPreview(null)} title={file?.name || '结果预览'} footer={<><Button variant="secondary" onClick={() => setPreview(null)}>关闭</Button><Button onClick={() => file && downloadFile(file.name, file.content, file.mime)}><Download size={15} />下载文件</Button></>}>{file?.mime === 'image/svg+xml' ? <><DomainPreview task={task} /><p className="cp-muted">下载文件包含可独立打开的领域结果示意图。</p></> : <pre className={styles.filePreview}>{file?.content}</pre>}</Modal></div>;
}

export function TaskDetail({ id }: { id: string }) {
  return <Suspense fallback={<div className="cp-note">正在加载任务详情…</div>}><TaskDetailContent key={id} id={id} /></Suspense>;
}

function TaskDetailContent({ id }: { id: string }) {
  const router = useRouter();
  const requestedTab = useSearchParams().get('tab');
  const { tasks, plans, datasets, models, tools, handoffs, updateTask, advanceTask, cloneTask, retryTask, addAsset } = useComputeStore();
  const task = tasks.find((item) => item.id === id);
  const [tab, setTab] = useState('概览');
  const [modal, setModal] = useState<'stop' | 'retry' | 'parameters' | 'asset' | 'confirm' | null>(null);
  const [resource, setResource] = useState('');
  const [parameters, setParameters] = useState<Parameter[]>([]);
  const [assetName, setAssetName] = useState('');
  const [message, setMessage] = useState('');
  const [errorAnalysis, setErrorAnalysis] = useState(false);
  const [confirmations, setConfirmations] = useState<string[]>([]);
  useEffect(() => { setTab(requestedTab && DETAIL_TABS.includes(requestedTab) ? requestedTab : '概览'); }, [id, requestedTab]);

  if (!task) return <Empty title="未找到此计算任务" description="任务可能尚未创建，或当前演示数据已被重置。" action={<Link className={styles.primaryLink} href="/compute-space/tasks">返回任务中心</Link>} />;
  const plan = task.planSnapshot || plans.find((item) => item.id === task.planId);
  const tool = tools.find((item) => item.id === task.toolId);
  const dataset = datasets.find((item) => item.id === task.datasetId);
  const model = models.find((item) => item.id === task.modelId);
  const versions = tasks.filter((item) => item.id === task.id || item.id === task.parentId || item.parentId === task.id || (task.parentId && item.parentId === task.parentId));
  const isFailed = ['失败', '资源不足', '等待人工处理'].includes(task.status);
  const editable = ['草稿', '待确认', '待提交'].includes(task.status);
  const stages = ['数据准备', '模型初始化', '求解计算', '结果生成'];
  const currentStage = task.status === '已完成' ? 4 : task.status === '结果生成中' ? 3 : task.status === '运行中' || isFailed || task.status === '暂停' ? 2 : task.status === '排队中' ? 0 : -1;

  function clone(version = false) { if (!task) return; const cloneId = cloneTask(task.id); if (version) updateTask(cloneId, { name: task.name, version: task.version + 1, parentId: task.id }); router.push(`/compute-space/tasks/${cloneId}`); }
  function openRetry() { if (!task) return; if (!tool || tool.status !== '已上架' || /过期|不可用/.test(tool.license)) { setMessage('无法重试：工具未上架或许可证不可用。请在科研工具工作台处理后重新提交。'); return; } setResource(task.resources.includes('128') ? task.resources.replace('128', '256') : `${task.resources} · 内存 256 GB`); setParameters(task.parameters.map((p) => ({ ...p }))); setModal('retry'); }
  function openParameters() { if (!task) return; setParameters(task.parameters.map((p) => ({ ...p }))); setModal('parameters'); }
  function saveParameters() { if (!task) return; const now = new Date().toISOString(); const changed = parameters.map((parameter, index) => parameter.value !== task.parameters[index]?.value ? { ...parameter, original: parameter.original ?? task.parameters[index]?.value, modifiedBy: '张博士', modifiedAt: now } : parameter); updateTask(task.id, { parameters: changed, ...(task.status === '待提交' ? { status: '待确认' as const, confirmations: [] } : {}), logs: [...task.logs, `[${new Date().toLocaleTimeString('zh-CN')}] [INFO] 张博士更新参数配置，原始方案参数已保留。`] }); }
  function advance() {
    if (!task) return;
    if (task.status === '草稿') {
      updateTask(task.id, { status: '待确认', logs: [...task.logs, `[${new Date().toLocaleTimeString('zh-CN')}] [INFO] 草稿提交配置审查，等待人工确认。`] });
      setMessage('草稿已提交，请确认研究目标、参数与计算资源。');
    } else if (['待确认', '待提交'].includes(task.status)) { setConfirmations([]); setModal('confirm'); }
    else if (task.status === '暂停') { updateTask(task.id, { status: '运行中', logs: [...task.logs, '[INFO] 从最近检查点恢复运行。'] }); setMessage('已从最近检查点恢复运行。'); }
    else { advanceTask(task.id); setMessage('演示计算状态已推进，运行阶段和完整日志已同步。'); }
  }

  return <div data-prd-id="REQ-DETAIL-001">
    <Link className={styles.backLink} href="/compute-space/tasks"><ArrowLeft size={15} /> 计算任务 <ChevronRight size={12} /> 任务详情</Link>
    <PageHeader title={task.name} description={`${task.id}　·　${task.project}　·　版本 V${task.version}`} actions={<><Button variant="secondary" onClick={() => clone(true)}><GitBranch size={15} /> 创建新版本</Button>{ACTIVE_STATES.includes(task.status) && <Button variant="secondary" onClick={() => setModal('stop')}><Square size={13} /> 停止</Button>}{EXCEPTION_STATES.includes(task.status) && task.status !== '暂停' ? <Button variant="primary" onClick={openRetry}><RotateCcw size={15} /> 修改后重试</Button> : task.status === '已完成' ? <Link className={styles.primaryLink} href={`/compute-space/handoff?task=${task.id}&direction=do`}><FlaskConical size={16} /> 生成实验方案</Link> : <Button variant="primary" onClick={advance}><Play size={14} />{nextLabel[task.status] || '继续计算'}</Button>}</>} />
    <div className={styles.detailMeta}><Status value={task.status} /><span><Clock3 size={14} />创建于 {formatTime(task.createdAt)}</span><span>运行时长 {task.duration}</span><span>创建人 {task.creator}</span><span className={styles.demoTag}>演示任务</span></div>
    {message && <div className="cp-note" role="status">{message}<button className={styles.inlineClose} onClick={() => setMessage('')} aria-label="关闭提示"><X size={14} /></button></div>}
    {isFailed && <div className={styles.failurePanel}><TriangleAlert size={24} /><div><strong>{task.status} · 求解阶段</strong><p>{task.error || '可用计算资源不满足当前任务要求。'} 当前结果无效，原始配置和日志已保留。</p><div className="cp-row"><Button variant="secondary" onClick={() => setErrorAnalysis(!errorAnalysis)}><Sparkles size={14} /> 让 AI 分析</Button><Button variant="secondary" onClick={openRetry}>修改后重试</Button><Button variant="ghost" onClick={() => clone()}>克隆任务</Button></div>{errorAnalysis && <div className={styles.failureAdvice}><strong>建议先调整内存与网格规模</strong><p>求解器在矩阵分解时的峰值内存需求超出配额。建议将内存提高至 256 GB，减少网格自由度，或降低单节点并行进程数。重试后需检查残差收敛，不能使用失败任务的部分结果。</p><button className="cp-link" onClick={() => setTab('日志')}>查看完整错误日志 <ArrowRight size={13} /></button></div>}</div></div>}
    <Tabs items={DETAIL_TABS} value={tab} onChange={setTab} />
    <div className={styles.tabContent}>
      {tab === '概览' && <div className={styles.detailLayout}><div className="cp-stack"><Panel title="研究目标" actions={<span className={styles.sectionIcon}><FlaskConical size={18} /></span>}><p className={styles.goalText}>{plan?.goal || '研究高温高压条件下岩体裂缝的扩展机制，分析温度、围压与材料参数对裂缝路径和应力分布的影响。'}</p><div className={styles.sourcePlan}><FileText size={19} /><div><span>来源计算方案</span><Link href={`/compute-space/agent?plan=${task.planId}`}>{plan?.title || task.planId}</Link></div><Status value={plan?.status || '已确认'} /></div></Panel><Panel title="计算进度" actions={<span className="cp-muted">{task.progress}% 已完成</span>}><div className={styles.stages}>{stages.map((stage, index) => <div key={stage} className={index < currentStage ? styles.stageDone : index === currentStage ? styles.stageActive : ''}><span>{index < currentStage ? <Check size={14} /> : index + 1}</span><strong>{stage}</strong><small>{index < currentStage ? '已完成' : index === currentStage ? task.status : '等待执行'}</small></div>)}</div><Progress value={task.progress} status={task.status} /><div className={styles.overviewActions}><span>任务队列：{task.queue}</span><button className="cp-link" onClick={() => setTab('运行')}>查看运行状态 <ArrowRight size={14} /></button></div></Panel><Panel title="最近运行日志" actions={<button className="cp-link" onClick={() => setTab('日志')}>完整日志 <ArrowRight size={14} /></button>}><div className={styles.compactLogs}>{task.logs.slice(-5).map((line, i) => <div key={i} className={line.includes('ERROR') ? styles.errorLog : ''}><Terminal size={13} /><code>{line}</code></div>)}{!task.logs.length && <p className="cp-muted">提交任务后会开始记录执行日志。</p>}</div></Panel></div><div className="cp-stack"><Panel title="任务配置"><dl className={styles.keyValues}><dt>计算类型</dt><dd>{task.type}</dd><dt>工具 / 软件</dt><dd>{tool?.name || task.toolId} <small>{task.toolVersion}</small></dd><dt>数据版本</dt><dd>{dataset?.name || task.datasetId} · V{dataset?.version || 1}</dd><dt>模型版本</dt><dd>{model?.name || task.modelId || '物理模型'} · V{model?.version || 1}</dd><dt>计算资源</dt><dd>{task.resources}</dd><dt>运行环境</dt><dd>{task.environment}</dd></dl></Panel><Panel title="实时监控" actions={<span className={styles.monitorLabel}><i />演示采样</span>}><ResourceCharts task={task} /></Panel></div></div>}
      {tab === '参数' && <div className="cp-stack"><Panel title="实际计算参数" actions={editable ? <Button variant="secondary" onClick={openParameters}><SlidersHorizontal size={15} />修改参数</Button> : <Button variant="secondary" onClick={() => clone(true)}><GitBranch size={15} />新建版本调整参数</Button>}><p className="cp-muted">每项参数保留原始方案值、运行值与修改记录。</p><div className="cp-table-wrap"><table className="cp-table"><thead><tr><th>参数</th><th>原始方案值</th><th>实际运行值</th><th>单位</th><th>来源</th><th>修改记录</th></tr></thead><tbody>{task.parameters.map((parameter, i) => <tr key={`${parameter.name}-${i}`}><td><strong>{parameter.name}</strong></td><td>{parameter.original ?? plan?.parameters.find((p) => p.name === parameter.name)?.value ?? parameter.value}</td><td><span className={parameter.original && parameter.original !== parameter.value ? styles.changedValue : ''}>{parameter.value}</span></td><td>{parameter.unit || '—'}</td><td>{parameter.source}</td><td>{parameter.modifiedBy ? <>{parameter.modifiedBy}<div className="cp-muted">{formatTime(parameter.modifiedAt || '')}</div></> : <span className="cp-muted">与原始方案一致</span>}</td></tr>)}</tbody></table></div>{!editable && <div className="cp-note"><Info size={16} />已提交任务的运行参数固定保存。调整后会形成新版本，以保证计算可以复现。</div>}</Panel><Panel title="约束与边界"><div className={styles.explainGrid}><div><strong>边界条件</strong><p>{resultSchema(task).domain === 'fracture' ? '三轴应力边界、恒温控制、准静态载荷；采用同一参考坐标系。' : '采用来源方案的输入范围、模型适用条件与控制变量，参数已随任务固定保存。'}</p></div><div><strong>求解约束</strong><p>非线性迭代最多 100 次，残差阈值 10⁻⁶；对异常收敛进行标记。</p></div><div><strong>适用范围</strong><p>{plan?.risks || '参数范围内的数值模拟，需完成网格无关性检验和实验验证。'}</p></div></div></Panel></div>}
      {tab === '输入' && <div className="cp-stack"><div className="cp-grid-3"><Panel title="输入数据集"><div className={styles.inputIcon}><Database size={25} /></div><h3 className={styles.inputTitle}>{dataset?.name || task.datasetId || '方案内置数据'}</h3><p className="cp-muted">版本 V{dataset?.version || 1} · {dataset?.rows.toLocaleString() || '12,480'} 条记录</p><dl className={styles.keyValues}><dt>数据来源</dt><dd>{dataset?.source || '实验测量与文献整理'}</dd><dt>质量评分</dt><dd>{dataset?.quality || 96} / 100</dd><dt>输入字段</dt><dd>{dataset?.columns || 8} 个字段</dd></dl><Link href="/compute-space/data" className="cp-link">查看数据处理与血缘 <ArrowRight size={14} /></Link></Panel><Panel title="输入模型"><div className={styles.inputIcon}><Layers3 size={25} /></div><h3 className={styles.inputTitle}>{model?.name || task.modelId || '方案定义的领域计算模型'}</h3><p className="cp-muted">版本 V{model?.version || 1} · {model?.type || '物理模型'}</p><dl className={styles.keyValues}><dt>适用范围</dt><dd>{model?.scope || plan?.hypothesis || '遵循当前领域计算方案约束'}</dd><dt>模型状态</dt><dd>{model?.status || '已校验'}</dd><dt>测试数据</dt><dd>{model?.testSet || '当前领域独立参考数据'}</dd></dl><Link href="/compute-space/models" className="cp-link">查看模型详情 <ArrowRight size={14} /></Link></Panel><Panel title="研究上下文"><div className={styles.inputIcon}><FileText size={25} /></div><h3 className={styles.inputTitle}>证据与研究假设</h3><p className="cp-muted">随任务固定的科研上下文</p><ul className={styles.contextList}>{(plan?.evidence.length ? plan.evidence : ['高温对岩体力学性质的影响研究', '真三轴实验参数记录', '裂缝扩展研究假设']).map((item, i) => <li key={i}><FileText size={14} />{item}</li>)}</ul><Link className="cp-link" href={`/compute-space/agent?plan=${task.planId}`}>追溯来源方案 <ArrowRight size={14} /></Link></Panel></div><Panel title="输入配置清单" actions={<Button variant="secondary" onClick={() => downloadFile(`${task.id}-输入配置.json`, taskManifest(task), 'application/json')}><Download size={15} />下载配置</Button>}><p className="cp-muted">已锁定来源方案、数据集与模型版本。复现任务时将使用相同的输入引用和工具环境。</p><pre className={styles.manifest}>{JSON.stringify({ task: task.id, plan: task.planId, dataset: `${task.datasetId}@v${dataset?.version || 1}`, model: `${task.modelId || 'physics'}@v${model?.version || 1}`, software: `${tool?.name || task.toolId}@${task.toolVersion}`, environment: task.environment }, null, 2)}</pre></Panel></div>}
      {tab === '运行' && <div className={styles.detailLayout}><div className="cp-stack"><Panel title="任务运行状态" actions={<Status value={task.status} />}><div className={styles.runHeadline}><strong>{task.progress}<small>%</small></strong><div><span>{task.status === '已完成' ? '所有计算阶段已完成' : stages[Math.max(0, currentStage)] || '等待提交'}</span><p>已运行 {task.duration} · {task.queue}</p></div></div><Progress value={task.progress} status={task.status} /><div className={styles.runStages}>{stages.map((stage, index) => <div key={stage}><span className={index < currentStage ? styles.doneStep : index === currentStage ? styles.currentStep : ''}>{index < currentStage ? <Check size={15} /> : index + 1}</span><div><strong>Stage {index + 1}　{stage}</strong><p>{['输入数据校验、单位与格式统一', '网格构建、边界条件与材料本构初始化', '热–力耦合迭代求解、残差检查', '提取指标、生成图表与计算报告'][index]}</p></div><Status value={index < currentStage ? '已完成' : index === currentStage ? task.status : '等待'} /></div>)}</div><div className="cp-row">{task.status === '运行中' && <Button variant="secondary" onClick={() => updateTask(task.id, { status: '暂停', logs: [...task.logs, '[INFO] 用户暂停任务，保存计算检查点。'] })}><Pause size={15} />暂停</Button>}{task.status === '暂停' && <Button onClick={() => updateTask(task.id, { status: '运行中', logs: [...task.logs, '[INFO] 从最近检查点恢复运行。'] })}><Play size={15} />恢复运行</Button>}{ACTIVE_STATES.includes(task.status) && <Button variant="primary" onClick={advance}><Play size={15} />推进演示</Button>}<Button variant="ghost" onClick={() => setTab('日志')}><Terminal size={15} />查看日志</Button></div></Panel><Panel title="资源使用曲线" actions={<span className="cp-muted">20 分钟采样 · 演示数据</span>}><ResourceCharts task={task} /></Panel></div><div className="cp-stack"><Panel title="运行配置"><dl className={styles.keyValues}><dt>任务队列</dt><dd>{task.queue}</dd><dt>分配资源</dt><dd>{task.resources}</dd><dt>运行环境</dt><dd>{task.environment}</dd><dt>计算节点</dt><dd>compute-node-03</dd><dt>工作目录</dt><dd>/workspace/{task.id}</dd><dt>工具版本</dt><dd>{tool?.name || task.toolId} {task.toolVersion}</dd></dl></Panel><div className={styles.scienceNote}><Cpu size={20} /><div><strong>可交互的演示计算</strong><p>点击「推进演示」依次完成排队、求解和结果生成，状态与日志同步保留。</p></div></div></div></div>}
      {tab === '日志' && <LogViewer task={task} />}
      {tab === '结果' && <ResultFiles task={task} onAsset={(name) => { setAssetName(name); setModal('asset'); }} />}
      {tab === '分析' && <TaskAnalysis task={task} />}
      {tab === '版本与追溯' && <div className="cp-stack"><Panel title="完整计算链路" actions={<Button variant="secondary" onClick={() => downloadFile(`${task.id}-追溯清单.json`, taskManifest(task), 'application/json')}><Download size={15} />导出追溯清单</Button>}><div className={styles.lineage}>{[{ icon: FileText, title: '研究方案', value: plan?.title || task.planId, detail: `方案 V${plan?.version || 1}` }, { icon: Database, title: '数据与模型', value: dataset?.name || task.datasetId, detail: `数据 V${dataset?.version || 1} / 模型 V${model?.version || 1}` }, { icon: Cpu, title: '计算任务', value: task.name, detail: `${task.id} · V${task.version}` }, { icon: FolderOpen, title: '结果与评价', value: task.status === '已完成' ? `${task.resultCount} 项产物` : '等待结果生成', detail: task.review || '待人工分析' }].map((item, index) => <div key={item.title}><item.icon size={22} /><small>{item.title}</small><strong>{item.value}</strong><span>{item.detail}</span>{index < 3 && <ArrowRight size={16} className={styles.lineageArrow} />}</div>)}</div></Panel><Panel title="任务版本" actions={<Button variant="secondary" onClick={() => clone(true)}><GitBranch size={15} />创建新版本</Button>}><div className="cp-table-wrap"><table className="cp-table"><thead><tr><th>版本</th><th>任务</th><th>来源</th><th>状态</th><th>创建时间</th><th>操作</th></tr></thead><tbody>{versions.map((item) => <tr key={item.id}><td>V{item.version}{item.id === id && <span className={styles.currentTag}>当前</span>}</td><td>{item.name}<div className="cp-muted">{item.id}</div></td><td>{item.parentId ? `继承自 ${item.parentId}` : '原始计算方案'}</td><td><Status value={item.status} /></td><td>{formatTime(item.createdAt)}</td><td><Link href={`/compute-space/tasks/${item.id}`} className="cp-link">查看版本</Link></td></tr>)}</tbody></table></div></Panel><div className="cp-grid-2"><Panel title="人工确认与变更"><div className={styles.auditList}><div><ShieldCheck size={17} /><div><strong>计算配置确认</strong><p>{task.confirmations.length ? task.confirmations.join('；') : '尚未完成人工确认'}</p></div></div>{task.parameters.filter((p) => p.modifiedBy).map((p) => <div key={p.name}><SlidersHorizontal size={17} /><div><strong>{p.name}：{p.original} → {p.value} {p.unit}</strong><p>{p.modifiedBy} · {formatTime(p.modifiedAt || '')}</p></div></div>)}<div><CheckCircle2 size={17} /><div><strong>结果评价</strong><p>{task.review || '待人工分析'}</p></div></div></div></Panel><Panel title="跨空间流转" actions={<Link href={`/compute-space/handoff?task=${id}&direction=read`} className="cp-link">返回读空间研究</Link>}>{handoffs.filter((item) => item.taskId === id).length ? <div className={styles.auditList}>{handoffs.filter((item) => item.taskId === id).map((item) => <div key={item.id}><GitBranch size={17} /><div><strong>{item.direction} · {item.title}</strong><p>{formatTime(item.createdAt)} · {item.confirmed ? '已确认交接' : '待确认'}</p></div></div>)}</div> : <div className={styles.blankFlow}><GitBranch size={27} /><p>尚未发生跨空间流转</p><span>计算结果可生成实验方案，或返回读空间补充证据。</span></div>}</Panel></div></div>}
    </div>
    <Modal open={modal === 'stop'} onClose={() => setModal(null)} title="停止计算任务" footer={<><Button variant="secondary" onClick={() => setModal(null)}>继续计算</Button><Button variant="danger" onClick={() => { updateTask(id, { status: '取消', logs: [...task.logs, `[${new Date().toLocaleTimeString('zh-CN')}] [WARNING] 用户停止任务，计算资源已释放。`] }); setModal(null); setMessage('任务已停止，配置与完整日志已保留。'); }}>确认停止</Button></>}><p>将停止「{task.name}」并释放资源，尚未完成的结果不作为有效计算产物。</p><p className="cp-muted">已保存的参数、来源和日志仍可追溯，也可以克隆为新任务继续计算。</p></Modal>
    <Modal open={modal === 'parameters' || modal === 'retry'} onClose={() => setModal(null)} title={modal === 'retry' ? '调整配置并重新计算' : '编辑计算参数'} footer={<><Button variant="secondary" onClick={() => setModal(null)}>取消</Button><Button disabled={parameters.some((p) => !p.value.trim()) || (modal === 'retry' && !resource.trim())} onClick={() => { saveParameters(); if (modal === 'retry') { updateTask(id, { resources: resource }); retryTask(id); setMessage('已保存修改并重新提交任务，原始参数和运行日志可以追溯。'); } else setMessage('参数已更新，原始方案值和修改记录已保留。'); setModal(null); }}>{modal === 'retry' ? '确认修改并重试' : '保存参数'}</Button></>}>
      {modal === 'retry' && <><div className="cp-alert">失败阶段：求解阶段。建议增加内存、减少网格规模或调整并行参数。</div><label className="cp-field">计算资源<input className="cp-input" value={resource} onChange={(event) => setResource(event.target.value)} /></label></>}
      <div className="cp-grid-2">{parameters.map((p, index) => <label className="cp-field" key={`${p.name}-${index}`}>{p.name} {p.unit && `(${p.unit})`}<input className="cp-input" value={p.value} onChange={(event) => setParameters((current) => current.map((item, i) => i === index ? { ...item, value: event.target.value } : item))} /><small className="cp-muted">来源：{p.source}</small></label>)}</div>
    </Modal>
    <Modal open={modal === 'asset'} onClose={() => setModal(null)} title="保存为科研 Artifact" footer={<><Button variant="secondary" onClick={() => setModal(null)}>取消</Button><Button onClick={() => { addAsset(`${assetName} · ${task.name} · V${task.version}`); setModal(null); setMessage(`「${assetName}」已加入科研资产，任务来源与评价状态已保留。`); }}>确认保存</Button></>}><p><strong>{assetName}</strong></p><dl className={styles.keyValues}><dt>来源任务</dt><dd>{task.id}</dd><dt>任务版本</dt><dd>V{task.version}</dd><dt>评价状态</dt><dd>{task.review || '待人工分析'}</dd></dl><div className="cp-note">保存后可在科研资产中继续复用，未确认的解释保留待评价标记。</div></Modal>
    <Modal open={modal === 'confirm'} onClose={() => setModal(null)} title={task.status === '待确认' ? '确认计算配置' : '提交计算任务'} footer={<><Button variant="secondary" onClick={() => setModal(null)}>返回检查</Button><Button disabled={confirmations.length < 3 || !tool || tool.status !== '已上架' || /过期|不可用/.test(tool.license)} onClick={() => { updateTask(id, { confirmations: [...task.confirmations, ...confirmations], ...(task.status === '待确认' ? { status: '待提交' as const, logs: [...task.logs, '[INFO] 人工配置确认完成，任务待提交。'] } : {}) }); if (task.status === '待提交') advanceTask(id); setModal(null); setMessage('配置确认已记录，任务进入下一阶段。'); }}>确认并继续</Button></>}><div className="cp-note">请检查将用于本次计算的方案、输入与资源。确认记录会保存到任务追溯中。</div><dl className={styles.keyValues}><dt>来源方案</dt><dd>{plan?.title || task.planId}</dd><dt>计算工具</dt><dd>{tool?.name || task.toolId} {task.toolVersion}</dd><dt>申请资源</dt><dd>{task.resources}</dd></dl>{(!tool || tool.status !== '已上架' || /过期|不可用/.test(tool.license)) && <div className="cp-alert">当前工具未上架或许可证不可用，请先前往科研工具工作台处理。</div>}<div className={styles.confirmList}>{['已核对研究目标与计算方案', '已检查数据版本、模型和参数', '已确认资源申请与计算范围'].map((item) => <label key={item}><input type="checkbox" checked={confirmations.includes(item)} onChange={(event) => setConfirmations((current) => event.target.checked ? [...current, item] : current.filter((value) => value !== item))} />{item}</label>)}</div></Modal>
  </div>;
}




