export type TaskStatus = '草稿' | '待确认' | '待提交' | '排队中' | '运行中' | '结果生成中' | '已完成' | '暂停' | '失败' | '取消' | '资源不足' | '等待人工处理';
export interface Parameter { name: string; value: string; unit: string; source: string; original?: string; modifiedBy?: string; modifiedAt?: string }
export interface ComputePlan { projectId?: string; id: string; title: string; goal: string; hypothesis: string; project: string; method: string; toolId: string; datasetId: string; modelId: string; parameters: Parameter[]; outputs: string[]; resources: string; risks: string; evidence: string[]; version: number; status: '草稿' | '待确认' | '已确认' | '已创建任务' | '已失效'; createdAt: string }
export interface ComputeTask { projectId?: string; id: string; planId: string; planSnapshot?: ComputePlan; name: string; type: string; project: string; toolId: string; toolVersion: string; datasetId: string; modelId: string; parameters: Parameter[]; resources: string; environment: string; queue: string; status: TaskStatus; progress: number; createdAt: string; duration: string; creator: string; resultCount: number; error?: string; parentId?: string; version: number; confirmations: string[]; logs: string[]; conclusion: string; review: string }
export interface Dataset { headers?: string[]; preview?: string[][]; id: string; name: string; version: number; rows: number; columns: number; quality: number; source: string; parentId?: string; flow: string[]; createdAt: string; creator: string; usedBy: string[] }
export interface ResearchModel { trainingProgress?: number; trainingStartedAt?: string; id: string; name: string; version: number; type: string; datasetId: string; testSet: string; r2: number; rmse: number; mae: number; status: string; parameters: string; scope: string; createdAt: string }
export interface ScientificTool { id: string; name: string; type: string; domain: string; description: string; inputs: string; outputs: string; version: string; environment: string; license: string; status: string; favorite: boolean; schema: string; invocation: string; timeout: number; resource: string; tested: boolean }
export interface Handoff { id: string; direction: '算 → 做' | '算 → 读' | '做 → 算'; taskId: string; title: string; content: string; confirmed: boolean; createdAt: string }
export interface ComputeState { plans: ComputePlan[]; tasks: ComputeTask[]; datasets: Dataset[]; models: ResearchModel[]; tools: ScientificTool[]; handoffs: Handoff[]; activePlanId: string; references: string[]; assets: string[] }


