'use client';
import type { ButtonHTMLAttributes, ReactNode } from 'react';
import { X, Inbox } from 'lucide-react';
import * as Dialog from '@radix-ui/react-dialog';

export function Button({ variant = 'secondary', className = '', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'ghost' | 'danger' }) { return <button type="button" className={`cp-button cp-button-${variant} ${className}`} {...props} />; }
export function PageHeader({ eyebrow, title, description, actions }: { eyebrow?: string; title: string; description?: string; actions?: ReactNode }) { return <header className="cp-page-header"><div>{eyebrow && <div className="cp-eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description && <p>{description}</p>}</div>{actions && <div className="cp-row cp-header-actions">{actions}</div>}</header>; }
export function Panel({ title, actions, children, className = '' }: { title?: ReactNode; actions?: ReactNode; children: ReactNode; className?: string }) { return <section className={`cp-panel ${className}`}>{(title || actions) && <div className="cp-panel-heading"><h2>{title}</h2><div className="cp-row">{actions}</div></div>}<div className="cp-panel-body">{children}</div></section>; }
export function Status({ value }: { value: string }) { const kind = /失败|取消|过期|不足|淘汰|有偏差/.test(value) ? 'danger' : /完成|已确认|已评价|已发布|已上架|可用|一致|通过/.test(value) ? 'success' : /运行|训练|处理|生成中/.test(value) ? 'running' : /待|排队|暂停|验证|草稿/.test(value) ? 'warning' : 'neutral'; return <span className={`cp-status cp-status-${kind}`}><i />{value}</span>; }
export function Tabs({ items, value, onChange }: { items: string[]; value: string; onChange: (v: string) => void }) { return <div className="cp-tabs" role="tablist">{items.map(item => <button type="button" key={item} role="tab" aria-selected={value === item} className={value === item ? 'active' : ''} onClick={() => onChange(item)}>{item}</button>)}</div>; }
export function Modal({ open, onClose, title, children, footer }: { open: boolean; onClose: () => void; title: string; children: ReactNode; footer?: ReactNode }) { return <Dialog.Root open={open} onOpenChange={v => { if (!v) onClose(); }}><Dialog.Portal><Dialog.Overlay className="cp-modal-overlay"/><Dialog.Content className="cp-modal compute-space" aria-describedby={undefined}><div className="cp-modal-heading"><Dialog.Title>{title}</Dialog.Title><Dialog.Close asChild><button aria-label="关闭弹窗" className="cp-icon-button"><X size={18}/></button></Dialog.Close></div><div className="cp-modal-body">{children}</div>{footer && <div className="cp-modal-footer">{footer}</div>}</Dialog.Content></Dialog.Portal></Dialog.Root>; }
export function Empty({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <div className="cp-empty"><Inbox size={32}/><h3>{title}</h3>{description && <p>{description}</p>}{action}</div>; }
export function downloadFile(name: string, content: string, type = 'text/plain;charset=utf-8') { const url = URL.createObjectURL(new Blob([content], { type })); const a = document.createElement('a'); a.href = url; a.download = name; document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
