'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { ArrowRight, CheckCircle2, Download, Calculator, FlaskConical, LoaderCircle } from 'lucide-react';
import { toast } from 'sonner';
import { ReadPage, ReadPanel, ReadBadge, EmptyState, EvidenceLink, useReadTask, downloadText } from './ui';
import { READ_ROUTES, taskRoute, type HandoffDraft } from './types';
import { useReadStore } from './store';
import { useResearchProject } from '@/components/research/workspace-kit';

export function ReadHandoff() {
  const params=useSearchParams(); const s=useReadTask();const router=useRouter();const [confirmed,setConfirmed]=useState(false);
  const draft=s.drafts.find(d=>d.id===params.get('draft')&&d.projectId===s.project.id);
  if(!draft)return <ReadPage title="研究验证草稿"><EmptyState title="未找到当前课题的验证草稿" description="请从研究假设或提取数据创建计算或实验验证草稿。"><Link href={s.href(READ_ROUTES.home)} className="rs-primary-btn">返回读空间</Link></EmptyState></ReadPage>;
  const isCompute=draft.target==='compute';const source=s.tasks.find(t=>t.id===draft.taskId);const evidence=s.evidence.filter(e=>draft.evidenceIds.includes(e.id));
  const field=(label:string,key:keyof Pick<HandoffDraft,'goal'|'hypothesis'|'parameters'|'method'|'model'|'data'|'constraints'|'standardRequirements'>)=><label key={key} className="block text-xs font-medium text-slate-600">{label}<textarea aria-label={label} className="research-input mt-2 min-h-20 !text-sm" value={draft[key]} onChange={e=>s.updateDraft(draft.id,{[key]:e.target.value,confirmed:false})}/></label>;
  return <ReadPage title={isCompute?'科研计算任务草稿':'实验验证任务草稿'} description="研究目标、假设、关键参数与证据已一并带入。确认后进入下一科研阶段。" actions={<><ReadBadge tone="green">草稿已保存</ReadBadge><button className="rs-outline-btn" onClick={()=>downloadText(`${draft.title}.json`,JSON.stringify({...draft,evidence},null,2),'application/json')}><Download size={13}/>导出草稿</button></>}><div className="mx-auto grid max-w-5xl gap-5 lg:grid-cols-[minmax(0,1fr)_300px]"><ReadPanel title={draft.title}><div className="space-y-5">{field('研究目标','goal')}{field('候选科学假设','hypothesis')}{field('关键参数、单位与参数含义','parameters')}{field('推荐方法','method')}{isCompute&&field('候选模型','model')}{field('已有数据 / 文献实验条件','data')}{!isCompute&&field('标准要求','standardRequirements')}{field('约束条件','constraints')}</div></ReadPanel><div className="space-y-4"><ReadPanel title="来源与证据"><dl className="rs-data-list"><div><dt>来源任务</dt><dd>{source?<Link className="text-primary" href={taskRoute(source)}>{source.title}</Link>:draft.taskId}</dd></div><div><dt>所属课题</dt><dd>{s.project.name}</dd></div><div><dt>草稿状态</dt><dd>等待人工确认</dd></div></dl><div className="mt-4 space-y-3">{evidence.map(e=><div key={e.id} className="rounded border border-slate-100 p-3 text-xs"><EvidenceLink evidence={e}/><p className="my-2 text-muted-foreground">{e.excerpt}</p><ReadBadge tone={e.confirmed?'green':'amber'}>{e.confirmed?'来源已确认':'来源待核验'}</ReadBadge></div>)}</div></ReadPanel><div className="rs-confirm"><h3>进入{isCompute?'算空间':'做空间'}前确认</h3><p>当前内容为模拟研究草稿，参数、单位和来源均可继续编辑；不会提交到外部计算集群或实验设备。</p><label className="flex items-start gap-2 text-xs"><input className="mt-1" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>我已检查研究范围、参数单位与引用来源</label><button disabled={!confirmed||!draft.goal.trim()||!draft.parameters.trim()} className="rs-primary-btn mt-4 w-full" onClick={()=>{s.updateDraft(draft.id,{confirmed:true});if(source)s.updateTask(source.id,{confirmations:[...source.confirmations,`确认进入${isCompute?'算空间':'做空间'}：${draft.id}`]});router.push(`${s.href(isCompute?'/compute-space':'/experiment-design')}&readDraft=${draft.id}`);}}>确认并进入{isCompute?'算空间':'做空间'}<ArrowRight size={14}/></button></div></div></div></ReadPage>;
}

export function ReadDraftReceiver() {
  const params=useSearchParams();const {project,href}=useResearchProject();const s=useReadStore();const [ready,setReady]=useState(false);const [running,setRunning]=useState(false);const [progress,setProgress]=useState(0);
  useEffect(()=>{Promise.resolve(useReadStore.persist.rehydrate()).finally(()=>setReady(true));},[]);
  const draft=s.drafts.find(d=>d.id===params.get('readDraft')&&d.projectId===project.id&&d.confirmed);
  const result=s.artifacts.find(a=>a.taskId===draft?.taskId&&a.type===`验证结果:${draft?.id}`);
  useEffect(()=>{if(!running||!draft)return;const timer=setTimeout(()=>{if(progress<3)setProgress(p=>p+1);else {s.addArtifact({projectId:draft.projectId,taskId:draft.taskId,type:`验证结果:${draft.id}`,title:`${draft.target==='compute'?'模拟计算结果':'模拟实验方案'} · ${draft.title}`,content:`研究目标：${draft.goal}\n假设：${draft.hypothesis}\n参数：${draft.parameters}\n方法：${draft.method}\n\n${draft.target==='compute'?'敏感性分析模拟完成：关键参数的主效应与交互效应已生成。请基于模拟结果设计真实验证，不将演示数值视为科研结论。':'实验方案模拟生成：对照组与实验组各 3 个平行样，统一加载速率，记录温度、压力及观测指标；正式执行前需审核设备与安全条件。'}\n\n来源草稿：${draft.id}`,evidenceIds:draft.evidenceIds,confirmed:false,mode:'AI'});setRunning(false);toast.success('模拟结果已回流读空间任务');}},900);return()=>clearTimeout(timer);},[running,progress,draft,s]);
  if(!ready||!draft)return null;
  const target=draft.target==='compute'?'计算':'实验';
  return <section className="mb-5 rounded-xl border border-primary/25 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2 text-primary">{target==='计算'?<Calculator size={20}/>:<FlaskConical size={20}/>}<h2 className="font-semibold">来自读空间的{target}验证任务</h2><ReadBadge tone="green">已接收研究上下文</ReadBadge></div><Link className="text-xs text-primary" href={`${href(READ_ROUTES.handoff)}&draft=${draft.id}`}>查看完整草稿</Link></div><div className="mt-4 grid gap-4 text-sm md:grid-cols-3"><div><small className="text-muted-foreground">研究目标</small><p className="mt-1">{draft.goal}</p></div><div><small className="text-muted-foreground">关键参数</small><p className="mt-1">{draft.parameters}</p></div><div><small className="text-muted-foreground">验证方法 / 证据</small><p className="mt-1">{draft.method} · {draft.evidenceIds.length} 条来源证据</p></div></div>{running&&<p role="status" className="mt-4 flex items-center gap-2 text-sm text-primary"><LoaderCircle className="animate-spin" size={15}/>{['检查输入与单位','构建模拟验证方案','执行模拟验证','整理可追溯研究产物'][progress]}…</p>}{result?<div className="mt-4 rounded-lg bg-green-50 p-4 text-sm"><p className="mb-2 flex items-center gap-2 font-medium text-green-800"><CheckCircle2 size={16}/>模拟{target}已完成，结果已保存至研究任务</p><p className="whitespace-pre-wrap text-xs leading-6 text-slate-600">{result.content}</p><button className="research-button mt-3" onClick={()=>downloadText(`${result.title}.md`,result.content)}>导出结果</button></div>:<button disabled={running} className="research-primary mt-4" onClick={()=>{setProgress(0);setRunning(true);}}>{running?'模拟执行中…':target==='计算'?'启动模拟计算':'生成模拟实验方案'}</button>}</section>;
}
