'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Search, Plus, FileText, Play, Pause, ArrowUpRight, Download } from 'lucide-react';
import { ReadPage, ReadBadge, ReadTabs, EmptyState, useReadTask, formatDate, downloadText } from './ui';
import { READ_ROUTES, taskRoute, type TaskStatus } from './types';

export function ReadTasks() {
  const s=useReadTask(); const [filter,setFilter]=useState('全部'); const [query,setQuery]=useState(''); const [type,setType]=useState('全部类型');
  const tasks=s.tasks.filter(t=>t.projectId===s.project.id && (filter==='全部'||filter==='进行中'&&['规划中','执行中'].includes(t.status)||t.status===filter) && (type==='全部类型'||t.type===type) && `${t.title} ${t.goal}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));
  const tones:Record<TaskStatus,string>={'规划中':'neutral','执行中':'red','等待确认':'amber','已暂停':'neutral','已完成':'green','失败':'red'};
  return <ReadPage title="研究任务" description="恢复完整的研究工作区，继续计划、证据与研究产物。" actions={<Link className="rs-primary-btn" href={s.href(READ_ROUTES.home)}><Plus size={14}/>新建研究任务</Link>}><div className="rounded-lg border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><ReadTabs items={['全部','进行中','等待确认','已暂停','已完成','失败']} value={filter} onChange={setFilter}/><div className="rs-actions"><div className="flex items-center gap-2 rounded-md border border-slate-200 px-2"><Search size={13} className="text-muted-foreground"/><input aria-label="搜索研究任务" className="h-8 w-40 bg-transparent text-xs outline-none" placeholder="搜索任务名称或目标" value={query} onChange={e=>setQuery(e.target.value)}/></div><select className="research-input !h-8 !w-32 !text-xs" aria-label="研究任务类型" value={type} onChange={e=>setType(e.target.value)}>{['全部类型','科研思路探索','文献研读','多文献研读','标准对标','专利分析','图表提取','科研写作'].map(v=><option key={v}>{v}</option>)}</select></div></div>{tasks.length?<div className="rs-table-wrap"><table className="rs-task-table"><thead><tr><th>任务名称 / 研究目标</th><th>状态与进度</th><th>最近更新</th><th>产物</th><th>操作</th></tr></thead><tbody>{tasks.map(t=><tr key={t.id}><td><Link className="flex items-center gap-2 font-medium hover:text-primary" href={taskRoute(t)}><FileText size={16} className="shrink-0 text-primary"/>{t.title}</Link><p className="ml-6 mt-1 text-[11px] text-muted-foreground">{t.type} · {s.project.name}</p></td><td><ReadBadge tone={tones[t.status]}>{t.status}</ReadBadge><p className="mt-1 text-[10px] text-muted-foreground">{t.plan.filter(p=>p.done).length} / {t.plan.length} 步完成</p></td><td className="text-muted-foreground">{formatDate(t.updatedAt)}</td><td>{t.artifactIds.length}</td><td><div className="rs-actions"><Link className="rs-link-btn" href={taskRoute(t)}>继续研究<ArrowUpRight size={12}/></Link>{t.status==='执行中'?<button title="暂停任务" aria-label={`暂停${t.title}`} onClick={()=>s.updateTask(t.id,{status:'已暂停'})}><Pause size={13}/></button>:['已暂停','失败'].includes(t.status)?<button title="恢复任务" aria-label={`恢复${t.title}`} onClick={()=>s.updateTask(t.id,{status:'执行中',error:undefined})}><Play size={13}/></button>:null}<button title="导出任务" aria-label={`导出${t.title}`} onClick={()=>downloadText(`${t.title}.json`,JSON.stringify({task:t,artifacts:s.artifacts.filter(a=>a.taskId===t.id),evidence:s.evidence.filter(e=>e.taskId===t.id),notes:s.notes.filter(n=>n.taskId===t.id)},null,2),'application/json')}><Download size={13}/></button></div></td></tr>)}</tbody></table></div>:<EmptyState title={query||filter!=='全部'||type!=='全部类型'?'没有匹配的研究任务':'还没有研究任务'} description="创建任务后，执行记录、引用资料和科研产物会保存在这里。"><Link className="rs-primary-btn" href={s.href(READ_ROUTES.home)}>开始研究</Link></EmptyState>}<p className="mt-4 text-[11px] text-muted-foreground">共 {tasks.length} 项任务 · 已按最近更新时间排序 · 仅显示当前课题</p></div></ReadPage>;
}
