export type TaskStatus = '规划中' | '执行中' | '等待确认' | '已暂停' | '已完成' | '失败';
export type TaskType = '科研思路探索' | '文献研读' | '多文献研读' | '标准对标' | '专利分析' | '图表提取' | '科研写作';
export type PlanStep = { id: string; title: string; done: boolean };
export type Execution = { id: string; kind: '用户指令' | '研究发现' | '执行节点' | '人工确认'; text: string; time: string };
export type ResearchTask = { id: string; title: string; goal: string; type: TaskType; projectId: string; status: TaskStatus; mode: string; plan: PlanStep[]; resourceIds: string[]; artifactIds: string[]; stream: Execution[]; confirmations: string[]; updatedAt: string; createdAt: string; focus: string[]; hypothesis: string; error?: string };
export type Evidence = { id: string; projectId: string; taskId: string; sourceId: string; source: string; location: string; page: number; excerpt: string; confirmed: boolean; acquiredAt: string; access: '演示原文' | '仅摘要' | '用户上传' };
export type Artifact = { id: string; projectId: string; taskId: string; type: string; title: string; content: string; evidenceIds: string[]; version: number; mode: '人工' | 'AI' | '混合'; confirmed: boolean; updatedAt: string };
export type ResearchNote = { id: string; projectId: string; taskId: string; sourceId: string; text: string; author: '人工' | 'AI'; evidenceIds: string[]; updatedAt: string };
export type Resource = { id: string; name: string; kind: '文献' | '标准' | '专利' | '知识库' | '研究笔记' | '已有报告' | '计算结果' | '文件'; status: string; projectId: string; mime?: string; size?: number };
export type HandoffDraft = { id: string; projectId: string; taskId: string; target: 'compute' | 'experiment'; title: string; goal: string; hypothesis: string; parameters: string; evidenceIds: string[]; method: string; model: string; data: string; constraints: string; standardRequirements: string; createdAt: string; confirmed: boolean };
export const READ_ROUTES = { home: '/read-space', agent: '/read-space/agent', tasks: '/read-space/tasks', search: '/literature-search', reader: '/literature-search/1', standards: '/standards-benchmark', patents: '/patent-analysis', extraction: '/literature-search/data-extract', writing: '/research-writing', graph: '/knowledge-graph', handoff: '/read-space/handoff' };
export const DEFAULT_PLAN = ['明确研究问题', '生成检索策略', '搜集相关研究', '文献证据分析', '识别研究争议', '发现研究空白', '形成候选科学假设', '推荐研究路线'];
export function taskRoute(task: Pick<ResearchTask, 'id' | 'type' | 'projectId'>) { const path = ({ '文献研读': READ_ROUTES.reader, '多文献研读': READ_ROUTES.reader, '标准对标': READ_ROUTES.standards, '专利分析': READ_ROUTES.patents, '图表提取': READ_ROUTES.extraction, '科研写作': READ_ROUTES.writing } as Partial<Record<TaskType, string>>)[task.type] || READ_ROUTES.agent; return `${path}?task=${encodeURIComponent(task.id)}&projectId=${encodeURIComponent(task.projectId)}`; }
export function movePlanStep(plan: PlanStep[], id: string, direction: -1 | 1) { const index = plan.findIndex(s => s.id === id); const next = index + direction; if (index < 0 || next < 0 || next >= plan.length) return plan; const result = [...plan]; [result[index], result[next]] = [result[next], result[index]]; return result; }
export function draftFromTask(task: ResearchTask, target: HandoffDraft['target'], evidenceIds: string[], parameters: string): Omit<HandoffDraft, 'id' | 'createdAt' | 'confirmed'> { return { taskId: task.id, projectId: task.projectId, target, title: `${task.title} · ${target === 'compute' ? '计算验证' : '实验验证'}`, goal: task.goal, hypothesis: task.hypothesis, parameters, evidenceIds, method: target === 'compute' ? '参数敏感性分析' : '多因素对照实验', model: '待选择与验证', data: task.resourceIds.join('、'), constraints: '仅使用已确认的参数和证据；结果需人工复核', standardRequirements: '须核验现行标准及适用条款' }; }
