'use client';

import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { ArrowDown, ArrowUp, BookOpen, CheckCircle2, ChevronRight, Download, FileCheck2, FileText, Library, ListTree, Plus, Quote, Save, Search, ShieldCheck, Sparkles, Trash2 } from 'lucide-react';
import { useLocalState } from '@/components/research/workspace-kit';
import { downloadText, EmptyState, EvidenceLink, ReadBadge, ReadPage, ReadPanel, ReadTabs, useReadTask } from './ui';
import type { Artifact, Evidence } from './types';
import { findLiterature } from './literature';
import './extraction-writing.css';

type Chapter = { id: string; title: string; text: string };
type WritingData = { title: string; reportType: string; chapters: Chapter[]; current: string; selected: string[]; citationIds: string[]; draftId: string; reportId: string; taskId: string; confirmed: boolean; savedAt: string };
const reportTypes = ['文献综述', '技术调研报告', '课题研究报告', '阶段研究总结', '实验分析报告', '专题分析报告'];
const outlines: Record<string, string[]> = { '文献综述': ['研究背景与问题', '文献范围与检索方法', '主要研究进展', '不同观点与证据比较', '研究局限与空白', '结论与后续方向'], '技术调研报告': ['调研目标与范围', '技术路线现状', '关键指标对比', '应用条件与限制', '技术空白与建议'], '课题研究报告': ['课题背景与目标', '研究方案与方法', '阶段研究结果', '证据分析与讨论', '结论与研究计划'], '阶段研究总结': ['阶段目标与完成情况', '主要研究产物', '问题与证据缺口', '下一阶段计划'], '实验分析报告': ['实验目标与假设', '材料、方法与条件', '数据处理与结果', '误差分析与讨论', '结论与复现实验建议'], '专题分析报告': ['专题问题与范围', '证据来源与方法', '关键发现与观点比较', '适用边界与局限', '结论与建议'] };
const makeChapters = (type: string): Chapter[] => outlines[type].map((title, i) => ({ id: `chapter-${Date.now()}-${i}`, title, text: '' }));
function readableContent(artifact: Artifact) { try { const json = JSON.parse(artifact.content); if (json.rows) return `${json.caption || artifact.title}；包含 ${json.rows.length} 个数据点。参数：${json.xLabel || 'X'}（${json.xUnit || '待核验'}）与${json.yLabel || 'Y'}（${json.yUnit || '待核验'}）。`; if (json.chapters) return json.chapters.map((chapter: Chapter) => `${chapter.title}：${chapter.text}`).join('\n'); } catch { /* Human-readable artifact text. */ } return artifact.content; }
const xmlEscape = (text: string) => text.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]!);

export function ReadWriting() {
  const { project, task, createTask, href } = useReadTask();
  const params = useSearchParams(); const router = useRouter(); const pendingScope = useRef('');
  const taskId = task?.id; const queryTaskId = params.get('task');
  useEffect(() => {
    if (taskId) { pendingScope.current = ''; if (queryTaskId !== taskId) router.replace(href(`/research-writing?task=${encodeURIComponent(taskId)}`)); return; }
    const scope = `${project.id}:${queryTaskId || ''}`;
    if (pendingScope.current === scope) return;
    pendingScope.current = scope;
    const id = createTask(`${project.name} · 科研写作`, '科研写作', project.id);
    router.replace(href(`/research-writing?task=${encodeURIComponent(id)}`));
  }, [taskId, queryTaskId, project.id, project.name, createTask, href, router]);
  return taskId ? <WritingWorkspace key={`${project.id}-${taskId}`}/> : <div className="rs-empty" role="status">正在建立写作任务上下文…</div>;
}
function WritingWorkspace() {
  const ctx = useReadTask();
  const storedDraft = ctx.artifacts.find(a => a.projectId === ctx.project.id && a.taskId === ctx.task?.id && a.type === '报告草稿');
  let initial: WritingData = { title: `${ctx.project.name} · 文献综述`, reportType: '文献综述', chapters: [], current: '', selected: [], citationIds: [], draftId: '', reportId: '', taskId: ctx.task?.id || '', confirmed: false, savedAt: '' };
  const initialChapters = makeChapters(initial.reportType); initial = { ...initial, chapters: initialChapters, current: initialChapters[0].id };
  if (storedDraft) { try { const parsed = JSON.parse(storedDraft.content); if (Array.isArray(parsed.chapters) && parsed.chapters.length) initial = { ...initial, ...parsed, draftId: storedDraft.id }; } catch { /* Plain text report artifacts are not editable draft state. */ } }
  const [data, setData] = useLocalState<WritingData>(`ai4s-writing-${ctx.project.id}-${ctx.task!.id}`, initial);
  const [leftTab, setLeftTab] = useState('报告大纲'); const [scope, setScope] = useState('当前任务'); const [newChapter, setNewChapter] = useState(''); const [notice, setNotice] = useState(''); const [assistant, setAssistant] = useState<{ title: string; text: string } | null>(null); const [confirmOpen, setConfirmOpen] = useState(false); const [approval, setApproval] = useState(false); const [busy, setBusy] = useState(false);
  const current = data.chapters.find(chapter => chapter.id === data.current) || data.chapters[0];
  const currentTaskId = ctx.task!.id;
  const projectMaterials = ctx.artifacts.filter(artifact => artifact.projectId === ctx.project.id && !['报告草稿', '科研报告'].includes(artifact.type));
  const materials = projectMaterials.filter(artifact => scope === '当前课题' || artifact.taskId === currentTaskId);
  const selectedMaterials = projectMaterials.filter(artifact => data.selected.includes(artifact.id));
  const selectedEvidence = ctx.evidence.filter(evidence => evidence.projectId === ctx.project.id && selectedMaterials.some(material => material.evidenceIds.includes(evidence.id)));
  const citedEvidence = data.citationIds.map(id => ctx.evidence.find(evidence => evidence.id === id && evidence.projectId === ctx.project.id)).filter((evidence): evidence is Evidence => Boolean(evidence));
  const update = (patch: Partial<WritingData>) => setData(previous => ({ ...previous, ...patch, confirmed: false }));
  const editChapter = (patch: Partial<Chapter>) => update({ chapters: data.chapters.map(chapter => chapter.id === current.id ? { ...chapter, ...patch } : chapter) });
  const ensureTask = () => currentTaskId;
  const save = (formal = false) => {
    const taskId = ensureTask(); const savedAt = new Date().toISOString(); const stored = { ...data, taskId, savedAt, confirmed: formal };
    const input = { projectId: ctx.project.id, taskId, type: formal ? '科研报告' : '报告草稿', title: data.title, content: JSON.stringify(stored), evidenceIds: data.citationIds, mode: '混合' as const, confirmed: formal };
    const existingId = formal ? data.reportId : data.draftId; const existing = ctx.artifacts.find(artifact => artifact.id === existingId && artifact.projectId === ctx.project.id && artifact.taskId === taskId && artifact.type === input.type);
    const id = existing ? (ctx.updateArtifact(existing.id, input), existing.id) : ctx.addArtifact(input);
    setData(previous => ({ ...previous, taskId, savedAt, confirmed: formal, ...(formal ? { reportId: id } : { draftId: id }) }));
    if (formal) { const task = ctx.tasks.find(item => item.id === taskId); ctx.updateTask(taskId, { ...(task?.type === '科研写作' ? { status: '已完成' as const } : {}), confirmations: [...(task?.confirmations || []), `人工确认正式报告：${data.title} · ${new Date().toLocaleString('zh-CN')}`] }); setConfirmOpen(false); setNotice('正式科研报告已保存为独立产物，保留引用、来源和人工确认记录。'); } else setNotice('报告草稿已保存至当前研究任务。大纲与正文也会自动保存在本机。');
  };
  const loadExamples = () => {
    const taskId = ensureTask();
    const isCatalyst = /催化|CO₂/.test(ctx.project.name);
    const docIds = isCatalyst ? ['demo-lit-5', 'demo-lit-6', 'demo-lit-6'] : ['demo-lit-1', 'demo-lit-2', 'demo-lit-4'];
    const documents = docIds.map(id => findLiterature(id)!);
    const samples = [
      { title: `研究方法卡 · ${documents[0].method}`, type: '研究方法卡', location: 'P3 · 研究方法与实验条件', page: 3, excerpt: `演示证据：${documents[0].pages[2]?.text[0]} 温度范围 ${documents[0].temperature} ℃，压力范围 ${documents[0].pressure} MPa。`, confirmed: true },
      { title: '关键结论 · 参数影响', type: '文献研读卡', location: 'P4 · Table 2', page: 4, excerpt: `演示证据：${documents[1].conclusion} 结果仅适用于当前样本和实验条件，不能直接推广到其他材料或场景。`, confirmed: false },
      { title: '观点比较 · 适用条件与反向解释', type: '观点比较', location: isCatalyst ? 'P6 · 讨论与研究局限' : 'P1 · 摘要', page: isCatalyst ? 6 : 1, excerpt: `演示证据：${documents[2].conclusion} ${documents[2].limitation} 当前不能排除其他解释，需继续搜索反向证据。${isCatalyst ? '' : '目前仅摘要可用。'}`, confirmed: false },
    ];
    const ids = samples.map((sample, index) => { const evidenceId = ctx.addEvidence({ taskId, projectId: ctx.project.id, sourceId: docIds[index], source: documents[index].title, location: sample.location, page: sample.page, excerpt: sample.excerpt, confirmed: sample.confirmed, access: index === 2 && !isCatalyst ? '仅摘要' : '演示原文' }); return ctx.addArtifact({ taskId, projectId: ctx.project.id, type: sample.type, title: sample.title, content: sample.excerpt, evidenceIds: [evidenceId], mode: 'AI', confirmed: sample.confirmed }); });
    ctx.addResources(docIds, taskId);
    update({ taskId, selected: [...new Set([...data.selected, ...ids])] }); setLeftTab('研究素材'); setNotice('已载入 3 份演示研究素材，包含支持证据、反向证据和来源定位。');
  };
  const generateChapter = () => {
    if (current.text.trim()) { setAssistant({ title: '保留已有正文', text: '当前章节已有人工内容。助手将生成补充草稿并追加到正文，已有文字会保留。' }); }
    setBusy(true); setTimeout(() => {
      const citationIds = [...new Set([...data.citationIds, ...selectedEvidence.map(evidence => evidence.id)])];
      const materialText = selectedMaterials.map(artifact => { const references = artifact.evidenceIds.map(id => citationIds.indexOf(id) + 1).filter(index => index > 0).map(index => `[${index}]`).join(''); return `${artifact.title}：${readableContent(artifact).slice(0, 500)}${references}`; }).join('\n\n');
      const limited = selectedEvidence.length === 0 ? '当前尚无可引用证据，本章仅建立讨论框架，不形成确定性研究结论。需要补充相关文献、参数与原文定位后进一步撰写。' : selectedEvidence.length === 1 ? '当前仅有单一来源，应谨慎解释。此处结论仅在已记录的条件与范围内成立，仍需独立证据验证。' : '基于当前选定证据，可以形成初步分析；现有证据尚不能排除条件差异与选择偏倚，以下内容仍需人工审核。';
      const conflict = selectedMaterials.some(artifact => /争议|反向|冲突|不同.*趋势/.test(artifact.content));
      const text = `围绕“${ctx.project.name}”，本章讨论${current.title}。${limited}\n\n${materialText || '待补充材料：研究对象与适用范围、实验/计算方法、关键参数、原文结果及研究局限。'}\n\n${conflict ? '观点比较：现有素材包含反向或存在争议的证据。应分别说明各研究的条件差异，不将单一趋势视为普遍规律。' : '适用边界：应核验样本、实验条件、参数单位与方法假设，并通过进一步检索或验证评估可重复性。'}\n\n（模拟生成草稿；请结合原文进行人工编辑。）`;
      update({ chapters: data.chapters.map(chapter => chapter.id === current.id ? { ...chapter, text: chapter.text ? `${chapter.text}\n\n—— 基于所选证据的补充草稿 ——\n\n${text}` : text } : chapter), citationIds });
      setBusy(false); setAssistant({ title: '本章草稿已生成', text: `已引用 ${selectedEvidence.length} 条证据，使用 ${selectedMaterials.length} 份研究素材。${conflict ? '检测到存在争议的素材，已保留不同观点。' : ''}${selectedEvidence.some(evidence => evidence.access === '仅摘要') ? '部分来源仅摘要可用，已在来源列表标识。' : ''}` }); setNotice(`“${current.title}”草稿已生成，可以直接编辑正文。`);
    }, 600);
  };
  const insertEvidence = (evidence: Evidence) => { const citationIds = [...new Set([...data.citationIds, evidence.id])]; const number = citationIds.indexOf(evidence.id) + 1; update({ citationIds, chapters: data.chapters.map(chapter => chapter.id === current.id ? { ...chapter, text: `${chapter.text}${chapter.text ? '\n\n' : ''}${evidence.excerpt} [${number}]` } : chapter) }); setNotice(`已将证据 [${number}] 插入当前章节，并关联 ${evidence.location}。`); };
  const checkCitations = () => { const body = data.chapters.map(chapter => chapter.text).join('\n'); const matches = [...body.matchAll(/\[(\d+)\]/g)].map(match => Number(match[1])); const invalid = [...new Set(matches.filter(index => !data.citationIds[index - 1] || !ctx.evidence.some(evidence => evidence.id === data.citationIds[index - 1])))]; const longUncited = data.chapters.filter(chapter => chapter.text.length > 50 && !/\[\d+\]/.test(chapter.text)); setAssistant({ title: '引用检查结果', text: `检查范围：全部 ${data.chapters.length} 个章节。\n发现 ${matches.length} 处引用标记，引用 ${new Set(matches).size} 项来源。\n${invalid.length ? `无法匹配的引用：${invalid.map(index => `[${index}]`).join('、')}。` : '所有已有引用编号均可匹配来源。'}\n${longUncited.length ? `以下章节有较长正文但未引用证据：${longUncited.map(chapter => chapter.title).join('、')}。建议补充论据。` : '未发现有较长正文但完全没有引用的章节。'}\n${citedEvidence.filter(evidence => !evidence.confirmed).length} 条引用证据尚待人工确认。此检查只验证编号与覆盖情况，论据是否支持结论仍需人工核对。` }); };
  const checkSufficiency = () => { const controversy = selectedMaterials.some(artifact => /争议|反向|冲突/.test(artifact.content)); setAssistant({ title: controversy ? '存在争议 · 建议保留不同观点' : selectedEvidence.length > 1 ? '证据有限 · 仍需核对适用范围' : selectedEvidence.length ? '仅单一来源' : '当前证据不足', text: `当前选择 ${selectedMaterials.length} 份研究产物，关联 ${selectedEvidence.length} 条证据。其中已人工确认 ${selectedEvidence.filter(evidence => evidence.confirmed).length} 条，仅摘要可用 ${selectedEvidence.filter(evidence => evidence.access === '仅摘要').length} 条。\n${controversy ? '素材包含反向证据，不宜给出一致性或绝对结论。建议使用“在当前条件下”“初步提示”等谨慎表述，并分别比较研究条件。' : '建议逐条核对原文是否直接支持当前结论，并继续检索独立证据和反向结果。'}\n证据数量并不代表结论强度。` }); };
  const unifyTerms = () => { const terms = [['二氧化碳', 'CO₂'], ['CO2', 'CO₂'], ['页岩气藏', '页岩储层'], ['人工智能模型', 'AI 模型']]; let changes = 0; const chapters = data.chapters.map(chapter => { let text = chapter.text; for (const [from, to] of terms) { const count = text.split(from).length - 1; changes += count; text = text.split(from).join(to); } return { ...chapter, text }; }); update({ chapters }); setAssistant({ title: '术语统一完成', text: `${changes ? `已替换 ${changes} 处术语，修改已写入正文。` : '未发现需要替换的术语。'}\n术语表：二氧化碳 / CO2 → CO₂；页岩气藏 → 页岩储层；人工智能模型 → AI 模型。\n建议复核术语是否符合当前研究语境。` }); };
  const summary = () => { const sentences = current.text.split(/(?<=[。！？])\s*/).filter(sentence => sentence.trim() && !sentence.includes('模拟生成')); const text = sentences.length ? `本章小结：${sentences.slice(0, 2).join('').slice(0, 280)}\n现阶段结论仍受来源与实验条件限制，下一步应补充独立证据并核验适用范围。` : '本章小结：当前尚未形成有证据支撑的研究结论，需补充材料后继续分析。'; editChapter({ text: `${current.text}${current.text ? '\n\n' : ''}${text}` }); setAssistant({ title: '章节总结已插入', text: '已依据当前章节内容追加小结，保留了证据限制和下一步验证建议。' }); };
  const markdown = () => `# ${data.title}\n\n> ${data.reportType} · ${data.confirmed ? '已人工确认' : '草稿，待人工确认'}\n> 当前课题：${ctx.project.name}\n> 前端模拟研究工作台产物\n\n${data.chapters.map((chapter, index) => `## ${index + 1}. ${chapter.title}\n\n${chapter.text || '（待撰写）'}`).join('\n\n')}\n\n## 参考证据\n\n${citedEvidence.map((evidence, index) => `[${index + 1}] ${evidence.source}，${evidence.location}；${evidence.access}；${evidence.confirmed ? '已人工确认' : '待人工确认'}；获取时间：${evidence.acquiredAt}\n原文片段：${evidence.excerpt}`).join('\n\n') || '尚未插入引用。'}`;
  const exportHtml = () => { const html = `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>${xmlEscape(data.title)}</title><style>body{font:15px/1.9 system-ui,sans-serif;color:#28313b;max-width:850px;margin:50px auto;padding:0 24px}h1{font-size:29px}h2{font-size:21px;margin-top:35px}p{white-space:pre-wrap}small{color:#7d8690}article{border-bottom:1px solid #eee;padding-bottom:18px}@media print{body{margin:20px}}</style><body><h1>${xmlEscape(data.title)}</h1><small>${xmlEscape(data.reportType)} · ${data.confirmed ? '已人工确认' : '草稿，待人工确认'} · 前端模拟产物</small>${data.chapters.map((chapter, index) => `<article><h2>${index + 1}. ${xmlEscape(chapter.title)}</h2><p>${xmlEscape(chapter.text || '（待撰写）')}</p></article>`).join('')}<h2>参考证据</h2>${citedEvidence.map((evidence, index) => `<p>[${index + 1}] ${xmlEscape(evidence.source)} · ${xmlEscape(evidence.location)}<br><small>${xmlEscape(evidence.access)} · ${evidence.confirmed ? '已人工确认' : '待人工确认'} · ${xmlEscape(evidence.acquiredAt)}</small><br>${xmlEscape(evidence.excerpt)}</p>`).join('')}</body></html>`; downloadText(`${data.title}.html`, html, 'text/html;charset=utf-8'); setNotice('已导出可打印 HTML，包含全部章节及证据引用。'); };
  const moveChapter = (id: string, direction: -1 | 1) => { const chapters = [...data.chapters]; const index = chapters.findIndex(chapter => chapter.id === id); const next = index + direction; if (next < 0 || next >= chapters.length) return; [chapters[index], chapters[next]] = [chapters[next], chapters[index]]; update({ chapters }); };
  const addChapter = () => { if (!newChapter.trim()) { setNotice('请输入新章节名称。'); return; } const id = `chapter-${Date.now()}`; update({ chapters: [...data.chapters, { id, title: newChapter.trim(), text: '' }], current: id }); setNewChapter(''); };

  return <ReadPage title="科研报告撰写" description="以研究产物组织论述，以证据支撑每一个判断。" actions={<><ReadBadge tone={data.confirmed ? 'success' : 'neutral'}>{data.confirmed ? '已人工确认' : '写作草稿'}</ReadBadge><button className="rs-outline-btn" onClick={() => save()}><Save size={13}/>保存</button><button className="rs-outline-btn" onClick={() => { downloadText(`${data.title}.md`, markdown()); setNotice('已导出 Markdown，包含大纲、正文与证据引用。'); }}><Download size={13}/>Markdown</button><button className="rs-outline-btn" onClick={exportHtml}>HTML</button></>}>
    <div className="ew-sourcebar"><FileText size={16}/><select aria-label="报告类型" className="research-input ew-report-select" value={data.reportType} onChange={e => { update({ reportType: e.target.value, title: data.title.replace(data.reportType, e.target.value) }); setNotice('已切换报告类型。点击“生成大纲”可增加该类型缺少的章节，已有正文会保留。'); }}>{reportTypes.map(type => <option key={type}>{type}</option>)}</select><span>{ctx.task ? ctx.task.title : '独立写作工作区'} · {data.selected.length} 份素材</span><ReadBadge>模拟写作助手</ReadBadge></div>
    <div className="ew-writing-grid">
      <ReadPanel title="大纲与研究素材" actions={<ListTree size={14} className="text-muted-foreground"/>}>
        <ReadTabs items={['报告大纲', '研究素材']} value={leftTab} onChange={setLeftTab}/>
        {leftTab === '报告大纲' ? <><div className="ew-outline">{data.chapters.map((chapter, index) => <div key={chapter.id} className={`ew-outline-row ${current.id === chapter.id ? 'active' : ''}`}><button onClick={() => setData(previous => ({ ...previous, current: chapter.id }))}><strong>{String(index + 1).padStart(2, '0')}</strong><span>{chapter.title}</span>{chapter.text && <CheckCircle2 size={10}/>}</button><button className="ew-chapter-action" aria-label={`上移${chapter.title}`} disabled={index === 0} onClick={() => moveChapter(chapter.id, -1)}><ArrowUp size={11}/></button><button className="ew-chapter-action" aria-label={`下移${chapter.title}`} disabled={index === data.chapters.length - 1} onClick={() => moveChapter(chapter.id, 1)}><ArrowDown size={11}/></button><button className="ew-chapter-action" aria-label={`删除${chapter.title}`} disabled={data.chapters.length === 1} onClick={() => { const chapters = data.chapters.filter(item => item.id !== chapter.id); update({ chapters, current: current.id === chapter.id ? chapters[0].id : data.current }); }}><Trash2 size={11}/></button></div>)}</div>
          <div className="ew-outline-new"><input aria-label="新章节名称" className="research-input" placeholder="添加章节…" value={newChapter} onChange={e => setNewChapter(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') addChapter(); }}/><button className="rs-outline-btn" aria-label="添加章节" onClick={addChapter}><Plus size={13}/></button></div>
          <div className="ew-outline-controls"><button className="rs-outline-btn" onClick={() => { const missing = outlines[data.reportType].filter(title => !data.chapters.some(chapter => chapter.title === title)); const hasAnyText = data.chapters.some(chapter => chapter.text.trim()); const chapters = hasAnyText ? [...data.chapters, ...missing.map((title, index) => ({ id: `generated-${Date.now()}-${index}`, title, text: '' }))] : makeChapters(data.reportType); update({ chapters, current: chapters[0].id }); setNotice(`已生成${data.reportType}大纲${hasAnyText ? '，已有正文已保留' : ''}。`); }}><Sparkles size={12}/>生成大纲</button></div>
          <p className="rs-note mt-5">点击章节后，可直接修改正文中的章节标题。上下移动与新增章节会同步保留。</p>
        </> : <><div className="ew-writing-source-label"><span>素材范围</span><select aria-label="素材范围" value={scope} onChange={e => setScope(e.target.value)}><option>当前任务</option><option>当前课题</option></select></div><div className="ew-materials">{materials.map(artifact => <label className="ew-material" key={artifact.id}><input type="checkbox" checked={data.selected.includes(artifact.id)} onChange={e => update({ selected: e.target.checked ? [...data.selected, artifact.id] : data.selected.filter(id => id !== artifact.id) })}/><span><strong>{artifact.title}</strong><small>{artifact.type} · {artifact.evidenceIds.length} 条证据 · {artifact.confirmed ? '已确认' : '待确认'}</small></span></label>)}</div>{!materials.length && <EmptyState title="还没有研究素材" description="载入演示素材，或从研读、分析、提取工作台添加产物。"/>}<button className="rs-outline-btn mt-4 w-full" onClick={loadExamples}><Library size={12}/>载入示例素材</button></>}
      </ReadPanel>
      <section className="ew-editor-paper" aria-label="报告正文编辑器"><div className="ew-editor-toolbar"><div className="rs-actions"><button className="rs-link-btn" onClick={generateChapter} disabled={busy}><Sparkles size={13}/>{busy ? '正在组织证据…' : '生成本章草稿'}</button><button className="rs-link-btn" onClick={() => setLeftTab('研究素材')}><Quote size={12}/>选择证据</button></div><span>支持人工编辑 · 本机自动保留</span></div><div className="ew-editor-content"><textarea aria-label="报告标题" className="ew-document-title" rows={2} value={data.title} onChange={e => update({ title: e.target.value })}/><div className="ew-document-meta"><span>{data.reportType}</span><span>·</span><span>{data.chapters.length} 个章节</span><span>·</span><span>{citedEvidence.length} 项引用</span><span>·</span><span>{data.confirmed ? '正式报告' : '未确认草稿'}</span></div><input aria-label="当前章节标题" className="ew-chapter-title" value={current.title} onChange={e => editChapter({ title: e.target.value })}/><textarea aria-label="章节正文" className="ew-body-text" value={current.text} onChange={e => editChapter({ text: e.target.value })} placeholder={'开始撰写这一章…\n\n也可以先在左侧选择研究素材，再点击“生成本章草稿”。助手将按所选证据组织内容，并保留来源和适用边界。'}/>
        <div className="ew-reference-list"><h3>可引用证据 <span className="text-muted-foreground font-normal">({selectedEvidence.length})</span></h3>{selectedEvidence.length ? selectedEvidence.map(evidence => <div key={evidence.id}><div className="ew-reference-row"><span>{evidence.source}</span><button className="rs-link-btn shrink-0" onClick={() => insertEvidence(evidence)}><Plus size={10}/>引用</button></div><div className="rs-actions mt-1"><EvidenceLink evidence={evidence}/><ReadBadge tone={evidence.access === '仅摘要' ? 'warning' : 'neutral'}>{evidence.access}</ReadBadge></div></div>) : <p>选择研究产物后，其来源证据会显示在此处。<button className="rs-link-btn ml-2" onClick={loadExamples}>载入示例素材<ChevronRight size={11}/></button></p>}</div></div><footer className="ew-editor-footer"><span>{current.text.length} 字 · 第 {data.chapters.findIndex(chapter => chapter.id === current.id) + 1} 章</span><span>{data.savedAt ? `最近保存 ${new Date(data.savedAt).toLocaleTimeString('zh-CN')}` : '编辑内容保留在本机'}</span></footer></section>
      <ReadPanel title="AI 写作助手" actions={<Sparkles size={14} className="text-primary"/>}><div className="ew-assistant-intro"><ShieldCheck size={17}/><p>先组织证据，再形成论述。模拟助手保留分歧与不确定性。</p></div><div className="ew-assistant-actions"><button className="rs-outline-btn" onClick={generateChapter} disabled={busy}><Sparkles size={13}/>根据证据撰写</button><button className="rs-outline-btn" onClick={() => { setLeftTab('研究素材'); setAssistant({ title: '补充参考证据', text: '在左侧选择研究产物，正文下方会列出对应证据。点击“引用”将原文片段与引用标记加入当前章节。也可以继续检索相关文献。' }); }}><BookOpen size={13}/>补充参考文献</button><button className="rs-outline-btn" onClick={checkCitations}><Quote size={13}/>检查引用与无引用结论</button><button className="rs-outline-btn" onClick={checkSufficiency}><ShieldCheck size={13}/>检查论据充分性</button><button className="rs-outline-btn" onClick={unifyTerms}><CheckCircle2 size={13}/>统一专业术语</button><button className="rs-outline-btn" onClick={() => { const negative = selectedMaterials.filter(artifact => /反向|争议|冲突/.test(artifact.content)); setAssistant({ title: '不同观点比较', text: negative.length ? `当前素材中发现 ${negative.length} 份反向或争议证据：\n\n${negative.map(artifact => `${artifact.title}\n${readableContent(artifact)}`).join('\n\n')}\n\n建议按实验条件、样品和测量方法比较，而不是直接合并结论。` : '当前所选素材未包含明确的反向观点。这不代表不存在反向证据，请扩大检索范围并检查不同实验条件下的研究。' }); }}><ListTree size={13}/>比较不同观点</button><button className="rs-outline-btn" onClick={summary}><FileText size={13}/>生成章节总结</button><Link className="rs-outline-btn" href={ctx.href(`/literature-search?q=${encodeURIComponent(`${ctx.project.name} 反向证据 不一致 研究局限`)}${currentTaskId ? `&task=${currentTaskId}` : ''}`)}><Search size={13}/>寻找反向证据</Link></div>
        {assistant && <div className="ew-assistant-result" role="status"><strong>{assistant.title}</strong>{assistant.text}</div>}
        <div className="mt-5"><Link className="rs-link-btn" href={ctx.href(`/literature-search${currentTaskId ? `?task=${currentTaskId}` : ''}`)}>继续搜索证据<ChevronRight size={12}/></Link></div>
        <div className="ew-confirmation"><h3>形成正式科研报告</h3><p>正式报告需人工核验正文、引用与证据边界。确认后将生成可追溯的科研产物。</p><button className="rs-primary-btn w-full" onClick={() => { if (!data.chapters.some(chapter => chapter.text.trim())) { setNotice('请先撰写至少一个章节，再确认正式报告。'); return; } setConfirmOpen(true); setApproval(false); }}><FileCheck2 size={13}/>人工确认报告</button></div>
      </ReadPanel>
    </div>
    {notice && <div className="ew-status" role="status"><CheckCircle2 size={15}/>{notice}</div>}
    {confirmOpen && <section className="ew-confirmation" aria-label="正式报告人工确认"><h3>确认“{data.title}”</h3><p>已撰写 {data.chapters.filter(chapter => chapter.text.trim()).length} / {data.chapters.length} 个章节，引用 {citedEvidence.length} 条证据，其中 {citedEvidence.filter(evidence => !evidence.confirmed).length} 条尚未单独确认。{citedEvidence.length === 0 ? '当前无引用证据，正式报告应明确这是研究框架或计划，不应包含未经支撑的确定性结论。' : '请确保结论与证据的适用范围一致，并在正文说明现有分歧。'}该内容来自前端模拟工作台。</p><label><input type="checkbox" checked={approval} onChange={e => setApproval(e.target.checked)}/>我已核对正文、引用与研究局限，确认以当前内容形成正式报告。</label><div className="rs-actions"><button className="rs-primary-btn" disabled={!approval} onClick={() => save(true)}>确认并保存正式报告</button><button className="rs-outline-btn" onClick={() => setConfirmOpen(false)}>继续编辑</button><button className="rs-link-btn" onClick={checkCitations}>先检查引用</button></div></section>}
  </ReadPage>;
}
