import assert from 'node:assert/strict';
import { useComputeStore } from '../src/components/compute-space/store';

const s = useComputeStore;
s.persist.setOptions({ storage: { getItem: () => null, setItem: () => {}, removeItem: () => {} } });
s.getState().reset();
const initialCount = s.getState().tasks.length;
const planId = s.getState().createPlan('测试页岩温压敏感性');
assert.equal(s.getState().createTask(planId), '', '草稿不能直接提交');
s.getState().updatePlan(planId, { status: '已确认' });
const id = s.getState().createTask(planId);
assert.ok(id, '人工确认后创建任务');
assert.equal(s.getState().tasks.length, initialCount + 1);
let task = s.getState().tasks.find(t => t.id === id)!;
assert.equal(task.status, '排队中');
assert.equal(task.confirmations.length, 1);
assert.ok(s.getState().datasets.find(d => d.id === task.datasetId)!.usedBy.includes(id));
const originalGoal = s.getState().plans.find(p => p.id === planId)!.goal;
s.getState().updatePlan(planId, { goal: '修改后的目标', parameters: [{ name: '温度', value: '999', unit: '℃', source: '人工' }] });
task = s.getState().tasks.find(t => t.id === id)!;
assert.equal(task.planSnapshot?.goal, originalGoal, '任务必须保留创建时的方案快照');
assert.notEqual(task.parameters[0].value, '999', '运行参数与编辑参数隔离');
for (let i = 0; i < 9; i++) s.getState().advanceTask(id);
task = s.getState().tasks.find(t => t.id === id)!;
assert.equal(task.status, '已完成');
assert.equal(task.progress, 100);
assert.equal(task.resultCount, 7);
const before = task.logs.length;
s.getState().advanceTask(id);
assert.equal(s.getState().tasks.find(t => t.id === id)!.logs.length, before, '完成状态不继续推进');
const clone = s.getState().cloneTask(id);
assert.equal(s.getState().tasks.find(t => t.id === clone)!.parentId, id);
assert.equal(s.getState().tasks.find(t => t.id === clone)!.status, '草稿');
s.getState().advanceTask(clone);
assert.equal(s.getState().tasks.find(t => t.id === clone)!.status, '草稿', '克隆任务也不能跳过确认');
const failed = s.getState().tasks.find(t => t.status === '失败')!;
s.getState().updateTool(failed.toolId, { status: '已下架' });
s.getState().retryTask(failed.id);
assert.equal(s.getState().tasks.find(t => t.id === failed.id)!.status, '失败', '下架工具禁止重试');
s.getState().updateTool(failed.toolId, { status: '已上架', license: '许可证已过期' });
s.getState().retryTask(failed.id);
assert.equal(s.getState().tasks.find(t => t.id === failed.id)!.status, '失败', '过期许可禁止重试');
s.getState().updateTool(failed.toolId, { license: '可用 · 1 / 2 席' });
s.getState().retryTask(failed.id);
assert.equal(s.getState().tasks.find(t => t.id === failed.id)!.status, '排队中');
assert.ok(s.getState().tasks.find(t => t.id === failed.id)!.logs.some(l => l.includes('ERROR')), '重试保留失败证据');
const missing = s.getState().createPlan('缺失数据验证', { datasetId: 'absent' });
s.getState().updatePlan(missing, { status: '已确认' });
assert.equal(s.getState().createTask(missing), '', '引用不存在的数据版本不得提交');
const v2 = s.getState().newPlanVersion(planId);
assert.notEqual(v2, planId);
assert.equal(s.getState().plans.find(p => p.id === v2)!.version, 2);
assert.equal(s.getState().plans.find(p => p.id === v2)!.status, '草稿');
const first = s.getState().datasets[0];
const datasetId = s.getState().addDataset({ ...first, parentId: first.id, version: first.version + 1, headers: ['x', 'y'], preview: [['1', '2']] });
assert.equal(s.getState().datasets.find(d => d.id === datasetId)!.parentId, first.id);
assert.deepEqual(s.getState().datasets.find(d => d.id === datasetId)!.preview, [['1', '2']]);
console.log('Compute workflow checks passed: confirmation, snapshots, lifecycle, cloning, recovery, version lineage.');
